"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = ("DataType",)

class DataType:
    Wavefront: DataType = ...
    SpotRadius: DataType = ...
    Spot_X: DataType = ...
    Spot_Y: DataType = ...
    StrehlRation: DataType = ...
