"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

from __future__ import annotations

from zospy.api._ZOSAPI.Analysis import SampleSizes, SampleSizes_Pow2Plus1
from zospy.api._ZOSAPI.Analysis.Settings import IAS_

__all__ = ("IAS_DiffEfficiency2D", "IAS_DiffEfficiencyAngular", "IAS_DiffEfficiencyChromatic")

class IAS_DiffEfficiency2D(IAS_):
    @property
    def SampleSize(self) -> SampleSizes: ...
    @SampleSize.setter
    def SampleSize(self, value: SampleSizes) -> None: ...
    @property
    def Surface(self) -> IAS_Surface: ...
    @property
    def Field(self) -> IAS_Field: ...
    @property
    def Wavelength(self) -> IAS_Wavelength: ...
    @property
    def MinWavelength(self) -> float: ...
    @MinWavelength.setter
    def MinWavelength(self, value: float) -> None: ...
    @property
    def MaxWavelength(self) -> float: ...
    @MaxWavelength.setter
    def MaxWavelength(self, value: float) -> None: ...
    @property
    def MinAngle(self) -> float: ...
    @MinAngle.setter
    def MinAngle(self, value: float) -> None: ...
    @property
    def MaxAngle(self) -> float: ...
    @MaxAngle.setter
    def MaxAngle(self, value: float) -> None: ...
    @property
    def HologramObject(self) -> int: ...
    @HologramObject.setter
    def HologramObject(self, value: int) -> None: ...
    @property
    def AmbientObject(self) -> int: ...
    @AmbientObject.setter
    def AmbientObject(self, value: int) -> None: ...
    @property
    def DetectorObject(self) -> int: ...
    @DetectorObject.setter
    def DetectorObject(self, value: int) -> None: ...
    @property
    def srcPositionX(self) -> float: ...
    @srcPositionX.setter
    def srcPositionX(self, value: float) -> None: ...
    @property
    def srcPositionY(self) -> float: ...
    @srcPositionY.setter
    def srcPositionY(self, value: float) -> None: ...
    @property
    def srcPositionZ(self) -> float: ...
    @srcPositionZ.setter
    def srcPositionZ(self, value: float) -> None: ...
    @property
    def srcUnpolarized(self) -> bool: ...
    @srcUnpolarized.setter
    def srcUnpolarized(self, value: bool) -> None: ...
    @property
    def srcXTitled(self) -> bool: ...
    @srcXTitled.setter
    def srcXTitled(self, value: bool) -> None: ...
    @property
    def srcPolJx(self) -> float: ...
    @srcPolJx.setter
    def srcPolJx(self, value: float) -> None: ...
    @property
    def srcPolJy(self) -> float: ...
    @srcPolJy.setter
    def srcPolJy(self, value: float) -> None: ...
    @property
    def srcPrePropagation(self) -> float: ...
    @srcPrePropagation.setter
    def srcPrePropagation(self, value: float) -> None: ...
    @property
    def InsideOfObject(self) -> int: ...
    @InsideOfObject.setter
    def InsideOfObject(self, value: int) -> None: ...

class IAS_DiffEfficiencyAngular(IAS_):
    @property
    def SampleSize(self) -> SampleSizes_Pow2Plus1: ...
    @SampleSize.setter
    def SampleSize(self, value: SampleSizes_Pow2Plus1) -> None: ...
    @property
    def Surface(self) -> IAS_Surface: ...
    @property
    def Field(self) -> IAS_Field: ...
    @property
    def Wavelength(self) -> IAS_Wavelength: ...
    @property
    def MinAngle(self) -> float: ...
    @MinAngle.setter
    def MinAngle(self, value: float) -> None: ...
    @property
    def MaxAngle(self) -> float: ...
    @MaxAngle.setter
    def MaxAngle(self, value: float) -> None: ...
    @property
    def HologramObject(self) -> int: ...
    @HologramObject.setter
    def HologramObject(self, value: int) -> None: ...
    @property
    def AmbientObject(self) -> int: ...
    @AmbientObject.setter
    def AmbientObject(self, value: int) -> None: ...
    @property
    def DetectorObject(self) -> int: ...
    @DetectorObject.setter
    def DetectorObject(self, value: int) -> None: ...
    @property
    def srcPositionX(self) -> float: ...
    @srcPositionX.setter
    def srcPositionX(self, value: float) -> None: ...
    @property
    def srcPositionY(self) -> float: ...
    @srcPositionY.setter
    def srcPositionY(self, value: float) -> None: ...
    @property
    def srcPositionZ(self) -> float: ...
    @srcPositionZ.setter
    def srcPositionZ(self, value: float) -> None: ...
    @property
    def srcUnpolarized(self) -> bool: ...
    @srcUnpolarized.setter
    def srcUnpolarized(self, value: bool) -> None: ...
    @property
    def srcXTitled(self) -> bool: ...
    @srcXTitled.setter
    def srcXTitled(self, value: bool) -> None: ...
    @property
    def srcPolJx(self) -> float: ...
    @srcPolJx.setter
    def srcPolJx(self, value: float) -> None: ...
    @property
    def srcPolJy(self) -> float: ...
    @srcPolJy.setter
    def srcPolJy(self, value: float) -> None: ...
    @property
    def srcPrePropagation(self) -> float: ...
    @srcPrePropagation.setter
    def srcPrePropagation(self, value: float) -> None: ...
    @property
    def InsideOfObject(self) -> int: ...
    @InsideOfObject.setter
    def InsideOfObject(self, value: int) -> None: ...

class IAS_DiffEfficiencyChromatic(IAS_):
    @property
    def SampleSize(self) -> SampleSizes_Pow2Plus1: ...
    @SampleSize.setter
    def SampleSize(self, value: SampleSizes_Pow2Plus1) -> None: ...
    @property
    def Surface(self) -> IAS_Surface: ...
    @property
    def Field(self) -> IAS_Field: ...
    @property
    def Wavelength(self) -> IAS_Wavelength: ...
    @property
    def MinWavelength(self) -> float: ...
    @MinWavelength.setter
    def MinWavelength(self, value: float) -> None: ...
    @property
    def MaxWavelength(self) -> float: ...
    @MaxWavelength.setter
    def MaxWavelength(self, value: float) -> None: ...
    @property
    def HologramObject(self) -> int: ...
    @HologramObject.setter
    def HologramObject(self, value: int) -> None: ...
    @property
    def AmbientObject(self) -> int: ...
    @AmbientObject.setter
    def AmbientObject(self, value: int) -> None: ...
    @property
    def DetectorObject(self) -> int: ...
    @DetectorObject.setter
    def DetectorObject(self, value: int) -> None: ...
    @property
    def srcPositionX(self) -> float: ...
    @srcPositionX.setter
    def srcPositionX(self, value: float) -> None: ...
    @property
    def srcPositionY(self) -> float: ...
    @srcPositionY.setter
    def srcPositionY(self, value: float) -> None: ...
    @property
    def srcPositionZ(self) -> float: ...
    @srcPositionZ.setter
    def srcPositionZ(self, value: float) -> None: ...
    @property
    def srcUnpolarized(self) -> bool: ...
    @srcUnpolarized.setter
    def srcUnpolarized(self, value: bool) -> None: ...
    @property
    def srcXTitled(self) -> bool: ...
    @srcXTitled.setter
    def srcXTitled(self, value: bool) -> None: ...
    @property
    def srcPolJx(self) -> float: ...
    @srcPolJx.setter
    def srcPolJx(self, value: float) -> None: ...
    @property
    def srcPolJy(self) -> float: ...
    @srcPolJy.setter
    def srcPolJy(self, value: float) -> None: ...
    @property
    def srcPrePropagation(self) -> float: ...
    @srcPrePropagation.setter
    def srcPrePropagation(self, value: float) -> None: ...
    @property
    def InsideOfObject(self) -> int: ...
    @InsideOfObject.setter
    def InsideOfObject(self, value: int) -> None: ...
