"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

from zospy.api.stubs._ZOSAPI_constants.Editors import LDE, MCE, MFE, NCE, TDE

__all__ = (
    "LDE",
    "MCE",
    "MFE",
    "NCE",
    "TDE",
    "CellDataType",
    "DirectionOfRayTravel",
    "EditorType",
    "ReflectTransmitCode",
    "SampleSides",
    "Samplings",
    "SolveStatus",
    "SolveType",
)

class CellDataType:
    Integer: CellDataType = ...
    Double: CellDataType = ...
    String: CellDataType = ...

class DirectionOfRayTravel:
    inward: DirectionOfRayTravel = ...
    outward: DirectionOfRayTravel = ...

class EditorType:
    LDE: EditorType = ...
    NCE: EditorType = ...
    MFE: EditorType = ...
    TDE: EditorType = ...
    MCE: EditorType = ...

class ReflectTransmitCode:
    Success: ReflectTransmitCode = ...
    NoReflectDataInFile: ReflectTransmitCode = ...
    NoTransmitDataInFile: ReflectTransmitCode = ...

class SampleSides:
    Front: SampleSides = ...
    Back: SampleSides = ...

class Samplings:
    FiveDegrees: Samplings = ...
    TwoDegrees: Samplings = ...
    OneDegree: Samplings = ...

class SolveStatus:
    Success: SolveStatus = ...
    InvalidSolveType: SolveStatus = ...
    InvalidRow: SolveStatus = ...
    InvalidColumn: SolveStatus = ...
    PostSurfaceStopOnly: SolveStatus = ...
    InvalidMacro: SolveStatus = ...
    Failed: SolveStatus = ...

class SolveType:
    None_: SolveType = ...
    Fixed: SolveType = ...
    Variable: SolveType = ...
    SurfacePickup: SolveType = ...
    ZPLMacro: SolveType = ...
    MarginalRayAngle: SolveType = ...
    MarginalRayHeight: SolveType = ...
    ChiefRayAngle: SolveType = ...
    MarginalRayNormal: SolveType = ...
    ChiefRayNormal: SolveType = ...
    Aplanatic: SolveType = ...
    ElementPower: SolveType = ...
    CocentricSurface: SolveType = ...
    ConcentricSurface: SolveType = ...
    CocentricRadius: SolveType = ...
    ConcentricRadius: SolveType = ...
    FNumber: SolveType = ...
    ChiefRayHeight: SolveType = ...
    EdgeThickness: SolveType = ...
    OpticalPathDifference: SolveType = ...
    Position: SolveType = ...
    Compensator: SolveType = ...
    CenterOfCurvature: SolveType = ...
    PupilPosition: SolveType = ...
    MaterialSubstitute: SolveType = ...
    MaterialOffset: SolveType = ...
    MaterialModel: SolveType = ...
    Automatic: SolveType = ...
    Maximum: SolveType = ...
    PickupChiefRay: SolveType = ...
    ObjectPickup: SolveType = ...
    ConfigPickup: SolveType = ...
    ThermalPickup: SolveType = ...
    MarginPercent: SolveType = ...
    CA_fill: SolveType = ...
    DIA_fill: SolveType = ...
    DuplicateSag: SolveType = ...
    InvertSag: SolveType = ...
    FieldPickup: SolveType = ...
