# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"
  apt_packages:
    - pandoc
    - language-pack-en-base
  jobs:
    create_environment:
        - asdf plugin add uv
        - asdf install uv latest
        - asdf global uv latest
    build:
        html:
          - uvx hatch run docs:build -T -b html docs $READTHEDOCS_OUTPUT/html

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
