# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - pandoc
    - dotnet-runtime-7.0
    - language-pack-en-base
  jobs:
    pre_build:
      # Fake the existence of winreg
      - mkdir ./winreg
      - mkdir ./winreg/winreg
      - touch ./winreg/winreg/__init__.py
#      - printf '[build-system]\nrequires = ["flit_core >=3.2,<4"]\nbuild-backend = "flit_core.buildapi"\n[project]\nname = "winreg"\ndescription = "a fake version of winreg"\nversion = "1.0.0"\n' > ./winreg/pyproject.toml
      - >-
          printf '[build-system]\n
          requires = ["flit_core >=3.2,<4"]\n
          build-backend = "flit_core.buildapi"\n\n
          [project]\n
          name = "winreg"\n
          description = "a fake version of winreg"\n
          version = "1.0.0"\n' > ./winreg/pyproject.toml
      - cat ./winreg/pyproject.toml
      - pip install ./winreg

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
  # Fail on all warnings to avoid broken references
  # fail_on_warning: true

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf


# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - requirements: docs/requirements.txt