# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - pandoc
    - dotnet-runtime-7.0
    - locales
  jobs:
#    post_system_dependencies:
#      - su -c "locale-gen en_US.UTF-8"
    pre_build:
      # Configure the .NET runtime
      - export PYTHONNET_RUNTIME="coreclr"
      # Set the locale to en_US, otherwise zospy.api.config will crash
      - export LC_ALL="en_US.UTF-8"
      - export LC_CTYPE="en_US.UTF-8"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
  # Fail on all warnings to avoid broken references
  # fail_on_warning: true

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf


# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - requirements: docs/requirements.txt