"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "ColorRaysBy",
    "Patterns",
    "Reference",
    "ShowScales",
)

class ColorRaysBy:
    Fields: ColorRaysBy = ...
    Waves: ColorRaysBy = ...
    Config: ColorRaysBy = ...
    Wavelength: ColorRaysBy = ...

class Patterns:
    Square: Patterns = ...
    Hexapolar: Patterns = ...
    Dithered: Patterns = ...

class Reference:
    ChiefRay: Reference = ...
    Centroid: Reference = ...
    Middle: Reference = ...
    Vertex: Reference = ...

class ShowScales:
    ScaleBar: ShowScales = ...
    Box: ShowScales = ...
    Cross: ShowScales = ...
    Circle: ShowScales = ...
