"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "SettingsDataType",
    "ZemaxColor",
    "ZemaxOpacity",
)

class SettingsDataType:
    None_: SettingsDataType = ...
    Integer: SettingsDataType = ...
    Double: SettingsDataType = ...
    Float: SettingsDataType = ...
    String: SettingsDataType = ...
    Byte: SettingsDataType = ...
    Boolean: SettingsDataType = ...

class ZemaxColor:
    Default: ZemaxColor = ...
    Color1: ZemaxColor = ...
    Color2: ZemaxColor = ...
    Color3: ZemaxColor = ...
    Color4: ZemaxColor = ...
    Color5: ZemaxColor = ...
    Color6: ZemaxColor = ...
    Color7: ZemaxColor = ...
    Color8: ZemaxColor = ...
    Color9: ZemaxColor = ...
    Color10: ZemaxColor = ...
    Color11: ZemaxColor = ...
    Color12: ZemaxColor = ...
    Color13: ZemaxColor = ...
    Color14: ZemaxColor = ...
    Color15: ZemaxColor = ...
    Color16: ZemaxColor = ...
    Color17: ZemaxColor = ...
    Color18: ZemaxColor = ...
    Color19: ZemaxColor = ...
    Color20: ZemaxColor = ...
    Color21: ZemaxColor = ...
    Color22: ZemaxColor = ...
    Color23: ZemaxColor = ...
    Color24: ZemaxColor = ...
    NoColor: ZemaxColor = ...

class ZemaxOpacity:
    P100: ZemaxOpacity = ...
    P90: ZemaxOpacity = ...
    P80: ZemaxOpacity = ...
    P70: ZemaxOpacity = ...
    P60: ZemaxOpacity = ...
    P50: ZemaxOpacity = ...
    P40: ZemaxOpacity = ...
    P30: ZemaxOpacity = ...
    P20: ZemaxOpacity = ...
    P10: ZemaxOpacity = ...
    P00: ZemaxOpacity = ...
