"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "ACISExportVersion",
    "ArchiveFileStatus",
    "CADAngularToleranceType",
    "CADFileType",
    "CADToleranceType",
    "DataTypes",
    "EntryCompressionModes",
    "LensShape",
    "LensType",
    "QuickAdjustCriterion",
    "QuickAdjustType",
    "QuickFocusCriterion",
    "RayPatternType",
    "ScaleToUnits",
    "SplineSegmentsType",
    "ZemaxFileTypes",
)

class ACISExportVersion:
    Current: ACISExportVersion = ...
    V25: ACISExportVersion = ...
    V26: ACISExportVersion = ...
    V27: ACISExportVersion = ...
    V28: ACISExportVersion = ...
    V29: ACISExportVersion = ...
    V30: ACISExportVersion = ...

class ArchiveFileStatus:
    Okay: ArchiveFileStatus = ...
    InvalidVersion: ArchiveFileStatus = ...
    InvalidFile: ArchiveFileStatus = ...
    UnableToOpen: ArchiveFileStatus = ...

class CADAngularToleranceType:
    Low: CADAngularToleranceType = ...
    Medium: CADAngularToleranceType = ...
    High: CADAngularToleranceType = ...
    Presentation: CADAngularToleranceType = ...

class CADFileType:
    IGES: CADFileType = ...
    STEP: CADFileType = ...
    SAT: CADFileType = ...
    STL: CADFileType = ...
    SAB: CADFileType = ...
    ASAT: CADFileType = ...
    ASAB: CADFileType = ...
    MODEL: CADFileType = ...
    CATPART: CADFileType = ...
    CATPRODUCT: CADFileType = ...
    XCGM: CADFileType = ...
    ZMO: CADFileType = ...
    XT: CADFileType = ...
    XB: CADFileType = ...
    PRC: CADFileType = ...
    JT: CADFileType = ...
    N3MF: CADFileType = ...
    U3D: CADFileType = ...
    VRML: CADFileType = ...
    OBJ: CADFileType = ...

class CADToleranceType:
    N_TenEMinus4: CADToleranceType = ...
    N_TenEMinus5: CADToleranceType = ...
    N_TenEMinus6: CADToleranceType = ...
    N_TenEMinus7: CADToleranceType = ...

class DataTypes:
    NotSet: DataTypes = ...
    Boolean: DataTypes = ...
    Integer: DataTypes = ...
    IntegerArray: DataTypes = ...
    IntegerMatrix: DataTypes = ...
    Float: DataTypes = ...
    FloatArray: DataTypes = ...
    FloatMatrix: DataTypes = ...
    Double: DataTypes = ...
    DoubleArray: DataTypes = ...
    DoubleMatrix: DataTypes = ...
    String: DataTypes = ...
    StringArray: DataTypes = ...
    StringMatrix: DataTypes = ...
    ByteArray: DataTypes = ...
    Dictionary: DataTypes = ...
    Serializable: DataTypes = ...
    File: DataTypes = ...

class EntryCompressionModes:
    Auto: EntryCompressionModes = ...
    On: EntryCompressionModes = ...
    Off: EntryCompressionModes = ...

class LensShape:
    Unknown: LensShape = ...
    Equi: LensShape = ...
    Bi: LensShape = ...
    Plano: LensShape = ...
    Meniscus: LensShape = ...

class LensType:
    Other: LensType = ...
    Spherical: LensType = ...
    GRIN: LensType = ...
    Aspheric: LensType = ...
    Toroidal: LensType = ...

class QuickAdjustCriterion:
    SpotSizeRadial: QuickAdjustCriterion = ...
    SpotSizeXOnly: QuickAdjustCriterion = ...
    SpotSizeYOnly: QuickAdjustCriterion = ...
    AngularRadial: QuickAdjustCriterion = ...
    AngularXOnly: QuickAdjustCriterion = ...
    AngularYOnly: QuickAdjustCriterion = ...

class QuickAdjustType:
    Radius: QuickAdjustType = ...
    Thickness: QuickAdjustType = ...

class QuickFocusCriterion:
    SpotSizeRadial: QuickFocusCriterion = ...
    SpotSizeXOnly: QuickFocusCriterion = ...
    SpotSizeYOnly: QuickFocusCriterion = ...
    RMSWavefront: QuickFocusCriterion = ...

class RayPatternType:
    XYFan: RayPatternType = ...
    XFan: RayPatternType = ...
    YFan: RayPatternType = ...
    Ring: RayPatternType = ...
    List: RayPatternType = ...
    Random: RayPatternType = ...
    Grid: RayPatternType = ...
    SolidRing: RayPatternType = ...

class ScaleToUnits:
    Millimeters: ScaleToUnits = ...
    Centimeters: ScaleToUnits = ...
    Inches: ScaleToUnits = ...
    Meters: ScaleToUnits = ...

class SplineSegmentsType:
    N_016: SplineSegmentsType = ...
    N_032: SplineSegmentsType = ...
    N_064: SplineSegmentsType = ...
    N_128: SplineSegmentsType = ...
    N_256: SplineSegmentsType = ...
    N_512: SplineSegmentsType = ...

class ZemaxFileTypes:
    Unknown: ZemaxFileTypes = ...
    LMX: ZemaxFileTypes = ...
    User: ZemaxFileTypes = ...
