"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "DisplayAsTypes",
    "Distortions",
    "FFA_AberrationTypes",
    "FFA_DecompositionTypes",
    "FFA_DisplayTypes",
    "FFA_FieldShapes",
    "FFA_ShowAsTypes",
    "FieldScanDirections",
    "RayTraceType",
    "ZernikeCoefficientTypes",
)

class DisplayAsTypes:
    Percent: DisplayAsTypes = ...
    Absolute: DisplayAsTypes = ...

class Distortions:
    F_TanTheta: Distortions = ...
    F_Theta: Distortions = ...
    Cal_F_Theta: Distortions = ...
    Cal_F_TanTheta: Distortions = ...
    SMIA_TV: Distortions = ...

class FFA_AberrationTypes:
    Defocus: FFA_AberrationTypes = ...
    PrimaryAstigmatism: FFA_AberrationTypes = ...
    PrimaryComa: FFA_AberrationTypes = ...
    SpecifiedTerm: FFA_AberrationTypes = ...

class FFA_DecompositionTypes:
    ZernikeTerms: FFA_DecompositionTypes = ...

class FFA_DisplayTypes:
    Absolute: FFA_DisplayTypes = ...
    Relative: FFA_DisplayTypes = ...
    Average: FFA_DisplayTypes = ...

class FFA_FieldShapes:
    Rectangular: FFA_FieldShapes = ...
    Elliptical: FFA_FieldShapes = ...

class FFA_ShowAsTypes:
    GreyScale: FFA_ShowAsTypes = ...
    GreyScaleInverted: FFA_ShowAsTypes = ...
    FalseColor: FFA_ShowAsTypes = ...
    FalseColorInverted: FFA_ShowAsTypes = ...
    Icons: FFA_ShowAsTypes = ...

class FieldScanDirections:
    Plus_Y: FieldScanDirections = ...
    Plus_X: FieldScanDirections = ...
    Minus_Y: FieldScanDirections = ...
    Minus_X: FieldScanDirections = ...

class RayTraceType:
    DirectionCosines: RayTraceType = ...
    TangentAngle: RayTraceType = ...
    YmUmYcUc: RayTraceType = ...

class ZernikeCoefficientTypes:
    Fringe: ZernikeCoefficientTypes = ...
    Standard: ZernikeCoefficientTypes = ...
    Annular: ZernikeCoefficientTypes = ...
