"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "CriterionComps",
    "CriterionFields",
    "Criterions",
    "MonteCarloStatistics",
    "QSCriterions",
    "SetupCaches",
    "SetupChanges",
    "SetupModes",
    "SetupPolynomials",
    "TolerancingColumnName",
    "TolerancingOperand",
    "TolerancingParameterName",
)

class CriterionComps:
    OptimizeAll_DLS: CriterionComps = ...
    NONSEQOptimizeAll: CriterionComps = ...
    ParaxialFocus: CriterionComps = ...
    NONSEQNone: CriterionComps = ...
    NONSEQOptimizeAll_OD: CriterionComps = ...
    None_: CriterionComps = ...
    OptimizeAll_OD: CriterionComps = ...

class CriterionFields:
    NONSEQUserDefined: CriterionFields = ...
    Y_Symmetric: CriterionFields = ...
    XY_Symmetric: CriterionFields = ...
    UserDefined: CriterionFields = ...

class Criterions:
    NONSEQMeritFunction: Criterions = ...
    RMSSpotRadius: Criterions = ...
    RMSSpotX: Criterions = ...
    NONSEQUserScript: Criterions = ...
    RMSSpotY: Criterions = ...
    RMSWavefront: Criterions = ...
    MeritFunction: Criterions = ...
    GeometricMTFAverage: Criterions = ...
    GeometricMTFTan: Criterions = ...
    GeometricMTFSag: Criterions = ...
    DiffMTFAverage: Criterions = ...
    DiffMTFTan: Criterions = ...
    DiffMTFSag: Criterions = ...
    BoresightError: Criterions = ...
    RMSAngularRadius: Criterions = ...
    RMSAngularX: Criterions = ...
    RMSAngularY: Criterions = ...
    UserScript: Criterions = ...

class MonteCarloStatistics:
    Normal: MonteCarloStatistics = ...
    Uniform: MonteCarloStatistics = ...
    Parabolic: MonteCarloStatistics = ...

class QSCriterions:
    RMSSpotRadius: QSCriterions = ...
    RMSSpotX: QSCriterions = ...
    RMSSpotY: QSCriterions = ...
    RMSWavefront: QSCriterions = ...
    BoresightError: QSCriterions = ...
    RMSAngularRadius: QSCriterions = ...
    RMSAngularX: QSCriterions = ...
    RMSAngularY: QSCriterions = ...

class SetupCaches:
    RecomputeAll: SetupCaches = ...
    RecomputeChanged: SetupCaches = ...
    UsePolynomial: SetupCaches = ...

class SetupChanges:
    LinearDifference: SetupChanges = ...
    RSSDifference: SetupChanges = ...

class SetupModes:
    Sensitivity: SetupModes = ...
    InverseLimit: SetupModes = ...
    InverseIncrement: SetupModes = ...
    SkipSensitivity: SetupModes = ...

class SetupPolynomials:
    None_: SetupPolynomials = ...
    ThreeMinusTerm: SetupPolynomials = ...
    FiveMinusTerm: SetupPolynomials = ...

class TolerancingColumnName:
    UserMeritFunction: TolerancingColumnName = ...
    UserScript: TolerancingColumnName = ...
    RmsSpotRadius: TolerancingColumnName = ...
    RmsSpotX: TolerancingColumnName = ...
    RmsSpotY: TolerancingColumnName = ...
    RmsWavefrontError: TolerancingColumnName = ...
    MtfGeometricAverage: TolerancingColumnName = ...
    MtfGeometricTangential: TolerancingColumnName = ...
    MtfGeometricSaggital: TolerancingColumnName = ...
    MtfDiffractionAverage: TolerancingColumnName = ...
    MtfDiffractionTangential: TolerancingColumnName = ...
    MtfDiffractionSagittal: TolerancingColumnName = ...
    BoresightError: TolerancingColumnName = ...
    RmsAngularRadius: TolerancingColumnName = ...
    RmsAngularX: TolerancingColumnName = ...
    RmsAngularY: TolerancingColumnName = ...
    BackFocusChange: TolerancingColumnName = ...
    Unknown: TolerancingColumnName = ...

class TolerancingOperand:
    NULL: TolerancingOperand = ...
    TRAD: TolerancingOperand = ...
    TCUR: TolerancingOperand = ...
    TFRN: TolerancingOperand = ...
    TTHI: TolerancingOperand = ...
    TCON: TolerancingOperand = ...
    TSDI: TolerancingOperand = ...
    TSDX: TolerancingOperand = ...
    TSDY: TolerancingOperand = ...
    TSTX: TolerancingOperand = ...
    TSTY: TolerancingOperand = ...
    TIRX: TolerancingOperand = ...
    TIRY: TolerancingOperand = ...
    TIRR: TolerancingOperand = ...
    TPAR: TolerancingOperand = ...
    TEDV: TolerancingOperand = ...
    TEDX: TolerancingOperand = ...
    TEDY: TolerancingOperand = ...
    TETX: TolerancingOperand = ...
    TETY: TolerancingOperand = ...
    TETZ: TolerancingOperand = ...
    TUDX: TolerancingOperand = ...
    TUDY: TolerancingOperand = ...
    TUTX: TolerancingOperand = ...
    TUTY: TolerancingOperand = ...
    TUTZ: TolerancingOperand = ...
    TIND: TolerancingOperand = ...
    TABB: TolerancingOperand = ...
    TEXI: TolerancingOperand = ...
    SAVE: TolerancingOperand = ...
    COMP: TolerancingOperand = ...
    CPAR: TolerancingOperand = ...
    CEDV: TolerancingOperand = ...
    CMCO: TolerancingOperand = ...
    STAT: TolerancingOperand = ...
    TWAV: TolerancingOperand = ...
    TNPS: TolerancingOperand = ...
    TNPA: TolerancingOperand = ...
    TMCO: TolerancingOperand = ...
    TEZI: TolerancingOperand = ...
    TCMU: TolerancingOperand = ...
    SEED: TolerancingOperand = ...
    COMM: TolerancingOperand = ...
    TPAI: TolerancingOperand = ...
    TCIO: TolerancingOperand = ...
    TCEO: TolerancingOperand = ...
    TNMA: TolerancingOperand = ...
    CNPA: TolerancingOperand = ...
    CNPS: TolerancingOperand = ...
    TRLX: TolerancingOperand = ...
    TRLY: TolerancingOperand = ...
    TRLR: TolerancingOperand = ...
    TARX: TolerancingOperand = ...
    TARY: TolerancingOperand = ...
    TARR: TolerancingOperand = ...
    TEDR: TolerancingOperand = ...
    TSDR: TolerancingOperand = ...
    ISOA: TolerancingOperand = ...
    ISOB: TolerancingOperand = ...
    ISOC: TolerancingOperand = ...
    ISOD: TolerancingOperand = ...
    MPVT: TolerancingOperand = ...
    Unknown: TolerancingOperand = ...

class TolerancingParameterName:
    CompensatorSetting: TolerancingParameterName = ...
    ConfigurationNumber: TolerancingParameterName = ...
    CommentField: TolerancingParameterName = ...
    NominalValue: TolerancingParameterName = ...
    Surface: TolerancingParameterName = ...
    MinimumValue: TolerancingParameterName = ...
    MaximumValue: TolerancingParameterName = ...
    Surface1: TolerancingParameterName = ...
    Surface2: TolerancingParameterName = ...
    AdjustSurface: TolerancingParameterName = ...
    ParameterNumber: TolerancingParameterName = ...
    Layer: TolerancingParameterName = ...
    MaximumNumber: TolerancingParameterName = ...
    MinimumNumber: TolerancingParameterName = ...
    Code: TolerancingParameterName = ...
    RowNumber: TolerancingParameterName = ...
    ConfigurationParameter: TolerancingParameterName = ...
    Object: TolerancingParameterName = ...
    Data: TolerancingParameterName = ...
    FieldNumber: TolerancingParameterName = ...
    SamplingSetting: TolerancingParameterName = ...
    Units: TolerancingParameterName = ...
    Statistics: TolerancingParameterName = ...
    PivotPointOption: TolerancingParameterName = ...
    FieldSetting: TolerancingParameterName = ...
    TdeRowNumber: TolerancingParameterName = ...
    Undefined: TolerancingParameterName = ...
