"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

from zospy.api.stubs._ZOSAPI.Analysis.Settings import IAS_
from zospy.api.stubs._ZOSAPI.Analysis.RayTracing import PathAnalysisSortType

from zospy.api.stubs._ZOSAPI_constants.Analysis.RayTracing import PathAnalysisSortType

__all__ = ("IAS_PathAnalysis", "PathAnalysisSortType")

class IAS_PathAnalysis(IAS_):
    @property
    def RayDatabaseFile(self) -> str: ...
    @RayDatabaseFile.setter
    def RayDatabaseFile(self, value: str) -> None: ...
    @property
    def AvailableRayDatabaseFiles(self) -> list[str]: ...
    @property
    def FirstRay(self) -> int: ...
    @FirstRay.setter
    def FirstRay(self, value: int) -> None: ...
    @property
    def LastRay(self) -> int: ...
    @LastRay.setter
    def LastRay(self, value: int) -> None: ...
    @property
    def FilterString(self) -> str: ...
    @FilterString.setter
    def FilterString(self, value: str) -> None: ...
    @property
    def GeneratePathFilters(self) -> bool: ...
    @GeneratePathFilters.setter
    def GeneratePathFilters(self, value: bool) -> None: ...
    @property
    def RelativeMinimumFlux(self) -> float: ...
    @RelativeMinimumFlux.setter
    def RelativeMinimumFlux(self, value: float) -> None: ...
    @property
    def SortBy(self) -> PathAnalysisSortType: ...
    @SortBy.setter
    def SortBy(self, value: PathAnalysisSortType) -> None: ...

# PathAnalysisSortType is imported as constant
