"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

from zospy.api.stubs._ZOSAPI_constants.Analysis.Settings.RMS import (
    RMSField,
    RMSFieldMap,
)

__all__ = (
    "RMSField",
    "RMSFieldMap",
    "FieldDensities",
    "FocusDensities",
    "Method",
    "Orientations",
    "RayDensities",
    "ReferTo",
    "WaveDensities",
)

class FieldDensities:
    FieldDens_5: FieldDensities = ...
    FieldDens_10: FieldDensities = ...
    FieldDens_15: FieldDensities = ...
    FieldDens_20: FieldDensities = ...
    FieldDens_25: FieldDensities = ...
    FieldDens_30: FieldDensities = ...
    FieldDens_35: FieldDensities = ...
    FieldDens_40: FieldDensities = ...
    FieldDens_45: FieldDensities = ...
    FieldDens_50: FieldDensities = ...
    FieldDens_55: FieldDensities = ...
    FieldDens_60: FieldDensities = ...
    FieldDens_65: FieldDensities = ...
    FieldDens_70: FieldDensities = ...
    FieldDens_75: FieldDensities = ...
    FieldDens_80: FieldDensities = ...
    FieldDens_85: FieldDensities = ...
    FieldDens_90: FieldDensities = ...
    FieldDens_95: FieldDensities = ...
    FieldDens_100: FieldDensities = ...

class FocusDensities:
    FocusDens_5: FocusDensities = ...
    FocusDens_10: FocusDensities = ...
    FocusDens_15: FocusDensities = ...
    FocusDens_20: FocusDensities = ...
    FocusDens_25: FocusDensities = ...
    FocusDens_30: FocusDensities = ...
    FocusDens_35: FocusDensities = ...
    FocusDens_40: FocusDensities = ...
    FocusDens_45: FocusDensities = ...
    FocusDens_50: FocusDensities = ...
    FocusDens_55: FocusDensities = ...
    FocusDens_60: FocusDensities = ...
    FocusDens_65: FocusDensities = ...
    FocusDens_70: FocusDensities = ...
    FocusDens_75: FocusDensities = ...
    FocusDens_80: FocusDensities = ...
    FocusDens_85: FocusDensities = ...
    FocusDens_90: FocusDensities = ...
    FocusDens_95: FocusDensities = ...
    FocusDens_100: FocusDensities = ...

class Method:
    GaussQuad: Method = ...
    RectArray: Method = ...

class Orientations:
    Plus_Y: Orientations = ...
    Minus_Y: Orientations = ...
    Plus_X: Orientations = ...
    Minus_X: Orientations = ...

class RayDensities:
    RayDens_1: RayDensities = ...
    RayDens_32x32: RayDensities = ...
    RayDens_64x64: RayDensities = ...
    RayDens_2: RayDensities = ...
    RayDens_128x128: RayDensities = ...
    RayDens_3: RayDensities = ...
    RayDens_256x256: RayDensities = ...
    RayDens_4: RayDensities = ...
    RayDens_5: RayDensities = ...
    RayDens_512x512: RayDensities = ...
    RayDens_1024x1024: RayDensities = ...
    RayDens_6: RayDensities = ...
    RayDens_2048x2048: RayDensities = ...
    RayDens_7: RayDensities = ...
    RayDens_4096x4096: RayDensities = ...
    RayDens_8: RayDensities = ...
    RayDens_8192x8192: RayDensities = ...
    RayDens_9: RayDensities = ...
    RayDens_10: RayDensities = ...
    RayDens_16384x16384: RayDensities = ...
    RayDens_11: RayDensities = ...
    RayDens_12: RayDensities = ...
    RayDens_13: RayDensities = ...
    RayDens_14: RayDensities = ...
    RayDens_15: RayDensities = ...
    RayDens_16: RayDensities = ...
    RayDens_17: RayDensities = ...
    RayDens_18: RayDensities = ...
    RayDens_19: RayDensities = ...
    RayDens_20: RayDensities = ...

class ReferTo:
    ChiefRay: ReferTo = ...
    Centroid: ReferTo = ...

class WaveDensities:
    WaveDens_5: WaveDensities = ...
    WaveDens_10: WaveDensities = ...
    WaveDens_15: WaveDensities = ...
    WaveDens_20: WaveDensities = ...
    WaveDens_25: WaveDensities = ...
    WaveDens_30: WaveDensities = ...
    WaveDens_35: WaveDensities = ...
    WaveDens_40: WaveDensities = ...
    WaveDens_45: WaveDensities = ...
    WaveDens_50: WaveDensities = ...
    WaveDens_55: WaveDensities = ...
    WaveDens_60: WaveDensities = ...
    WaveDens_65: WaveDensities = ...
    WaveDens_70: WaveDensities = ...
    WaveDens_75: WaveDensities = ...
    WaveDens_80: WaveDensities = ...
    WaveDens_85: WaveDensities = ...
    WaveDens_90: WaveDensities = ...
    WaveDens_95: WaveDensities = ...
    WaveDens_100: WaveDensities = ...
