"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "LTEdgeSasmpling",
    "LTRaySampling",
    "NSCTraceOptions",
    "OPDMode",
    "RayStatus",
    "RaysType",
    "ZRDFormatType",
)

class LTEdgeSasmpling:
    S_1X_Low: LTEdgeSasmpling = ...
    S_4X: LTEdgeSasmpling = ...
    S_16X: LTEdgeSasmpling = ...
    S_64X: LTEdgeSasmpling = ...
    S_256X: LTEdgeSasmpling = ...

class LTRaySampling:
    S_1X_Low: LTRaySampling = ...
    S_4X: LTRaySampling = ...
    S_16X: LTRaySampling = ...
    S_64X: LTRaySampling = ...
    S_256X: LTRaySampling = ...
    S_1024X: LTRaySampling = ...

class NSCTraceOptions:
    None_: NSCTraceOptions = ...
    UsePolarization: NSCTraceOptions = ...
    UseSplitting: NSCTraceOptions = ...
    UsePolarizationSplitting: NSCTraceOptions = ...
    UseScattering: NSCTraceOptions = ...
    UsePolarizationScattering: NSCTraceOptions = ...
    UseSplittingScattering: NSCTraceOptions = ...
    UsePolarizationSplittingScattering: NSCTraceOptions = ...

class OPDMode:
    None_: OPDMode = ...
    Current: OPDMode = ...
    CurrentAndChief: OPDMode = ...

class RayStatus:
    Parent: RayStatus = ...
    Terminated: RayStatus = ...
    Reflected: RayStatus = ...
    Transmitted: RayStatus = ...
    Scattered: RayStatus = ...
    Diffracted: RayStatus = ...
    GhostedFrom: RayStatus = ...
    DiffractedFrom: RayStatus = ...
    ScatteredFrom: RayStatus = ...
    RayError: RayStatus = ...
    BulkScattered: RayStatus = ...
    WaveShifted: RayStatus = ...
    TIR: RayStatus = ...
    OrdinaryRay: RayStatus = ...
    ExtraordinaryRay: RayStatus = ...
    WaveShiftPL: RayStatus = ...

class RaysType:
    Real: RaysType = ...
    Paraxial: RaysType = ...

class ZRDFormatType:
    UncompressedFullData: ZRDFormatType = ...
    CompressedBasicData: ZRDFormatType = ...
    CompressedFullData: ZRDFormatType = ...
