"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "ISAberrationTypes",
    "ISFlipTypes",
    "ISSamplings",
    "ISShowAsTypes",
)

class ISAberrationTypes:
    None_: ISAberrationTypes = ...
    Geometric: ISAberrationTypes = ...
    Diffraction: ISAberrationTypes = ...

class ISFlipTypes:
    None_: ISFlipTypes = ...
    TopBottom: ISFlipTypes = ...
    LeftRight: ISFlipTypes = ...
    TopBottomLeftRight: ISFlipTypes = ...

class ISSamplings:
    None_: ISSamplings = ...
    X2: ISSamplings = ...
    X4: ISSamplings = ...
    X8: ISSamplings = ...
    X16: ISSamplings = ...
    X32: ISSamplings = ...
    X64: ISSamplings = ...

class ISShowAsTypes:
    SimulatedImage: ISShowAsTypes = ...
    SourceBitmap: ISShowAsTypes = ...
    PSFGrid: ISShowAsTypes = ...
