"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "HuygensMtfTypes",
    "MtfDataTypes",
    "MtfTypes",
    "ShowAsTypes",
    "SurfaceMtfTypes",
)

class HuygensMtfTypes:
    Modulation: HuygensMtfTypes = ...

class MtfDataTypes:
    Average: MtfDataTypes = ...
    Tangential: MtfDataTypes = ...
    Sagittal: MtfDataTypes = ...

class MtfTypes:
    Modulation: MtfTypes = ...
    Real: MtfTypes = ...
    Imaginary: MtfTypes = ...
    Phase: MtfTypes = ...
    SquareWave: MtfTypes = ...

class ShowAsTypes:
    GreyScale: ShowAsTypes = ...
    GreyScaleInverted: ShowAsTypes = ...
    FalseColor: ShowAsTypes = ...
    FalseColorInverted: ShowAsTypes = ...

class SurfaceMtfTypes:
    MTF_Incoherent: SurfaceMtfTypes = ...
    Real_Incoherent: SurfaceMtfTypes = ...
    Imaginary_Incoherent: SurfaceMtfTypes = ...
    MTF_Coherent: SurfaceMtfTypes = ...
    Real_Coherent: SurfaceMtfTypes = ...
    Imaginary_Coherent: SurfaceMtfTypes = ...
