"""
This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

from __future__ import annotations

from zospy.api._ZOSAPI.Analysis.Settings import (
    IAS_,
    IAS_Field,
    IAS_Surface,
    IAS_Wavelength,
)

__all__ = ("ColorRaysBy", "IAS_Spot", "Patterns", "Reference", "ShowScales")

class ColorRaysBy:
    Fields = 0
    Waves = 1
    Config = 2
    Wavelength = 3

class IAS_Spot(IAS_):
    @property
    def ColorRaysBy(self) -> ColorRaysBy: ...
    @property
    def Configuration(self) -> int: ...
    @property
    def DeltaFocus(self) -> float: ...
    @property
    def DirectionCosines(self) -> bool: ...
    @property
    def Exaggerate(self) -> float: ...
    @property
    def Field(self) -> IAS_Field: ...
    @property
    def IgnoreLateralColor(self) -> bool: ...
    @property
    def Pattern(self) -> Patterns: ...
    @property
    def PlotScale(self) -> float: ...
    @property
    def RayDensity(self) -> int: ...
    @property
    def ReferTo(self) -> Reference: ...
    @property
    def ScatterRays(self) -> bool: ...
    @property
    def ShowAiryDisk(self) -> bool: ...
    @property
    def ShowScale(self) -> ShowScales: ...
    @property
    def Surface(self) -> IAS_Surface: ...
    @property
    def UsePolarization(self) -> bool: ...
    @property
    def UseSymbols(self) -> bool: ...
    @property
    def Wavelength(self) -> IAS_Wavelength: ...
    @ColorRaysBy.setter
    def ColorRaysBy(self, value: ColorRaysBy) -> None: ...
    @Configuration.setter
    def Configuration(self, value: int) -> None: ...
    @DeltaFocus.setter
    def DeltaFocus(self, value: float) -> None: ...
    @DirectionCosines.setter
    def DirectionCosines(self, value: bool) -> None: ...
    @Exaggerate.setter
    def Exaggerate(self, value: float) -> None: ...
    @IgnoreLateralColor.setter
    def IgnoreLateralColor(self, value: bool) -> None: ...
    @Pattern.setter
    def Pattern(self, value: Patterns) -> None: ...
    @PlotScale.setter
    def PlotScale(self, value: float) -> None: ...
    @RayDensity.setter
    def RayDensity(self, value: int) -> None: ...
    @ReferTo.setter
    def ReferTo(self, value: Reference) -> None: ...
    @ScatterRays.setter
    def ScatterRays(self, value: bool) -> None: ...
    @ShowAiryDisk.setter
    def ShowAiryDisk(self, value: bool) -> None: ...
    @ShowScale.setter
    def ShowScale(self, value: ShowScales) -> None: ...
    @UsePolarization.setter
    def UsePolarization(self, value: bool) -> None: ...
    @UseSymbols.setter
    def UseSymbols(self, value: bool) -> None: ...

class Patterns:
    Square = 0
    Hexapolar = 1
    Dithered = 2

class Reference:
    ChiefRay = 0
    Centroid = 1
    Middle = 2
    Vertex = 3

class ShowScales:
    ScaleBar = 0
    Box = 1
    Cross = 2
    Circle = 3
