"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "BackgroundColors",
    "DateTimeType",
    "EncodingType",
    "LanguageType",
    "ShowLineAsType",
    "ZemaxThemes",
)

class BackgroundColors:
    Default: BackgroundColors = ...
    White: BackgroundColors = ...
    LightGray: BackgroundColors = ...
    Gray: BackgroundColors = ...
    DarkGray: BackgroundColors = ...
    Black: BackgroundColors = ...

class DateTimeType:
    None_: DateTimeType = ...
    Date: DateTimeType = ...
    DateTime: DateTimeType = ...

class EncodingType:
    ANSI: EncodingType = ...
    Unicode: EncodingType = ...

class LanguageType:
    Chinese: LanguageType = ...
    English: LanguageType = ...
    Japanese: LanguageType = ...

class ShowLineAsType:
    TextAbove: ShowLineAsType = ...
    FileName: ShowLineAsType = ...
    ConfigurationNumber: ShowLineAsType = ...

class ZemaxThemes:
    Classic: ZemaxThemes = ...
    Dark: ZemaxThemes = ...
