"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

from zospy.api.stubs._ZOSAPI.Analysis.Settings import (
    IAS_,
    IAS_Field,
    IAS_Surface,
    IAS_Wavelength,
)
from zospy.api.stubs._ZOSAPI.Analysis.Tolerancing import (
    ITolerancingOperand,
    ITolerancingOperands,
    QYCompensations,
    QYCompensatorStrategy,
    QYPrecisions,
    ShowAsISO,
)
from zospy.api.stubs._ZOSAPI.Tools.Tolerancing import MonteCarloStatistics
from zospy.api.stubs._ZOSAPI.Analysis.Tolerancing.QuickYield import IAS_QYField

from zospy.api.stubs._ZOSAPI_constants.Analysis.Tolerancing import (
    QYCompensations,
    QYCompensatorStrategy,
    QYPrecisions,
    ShowAsISO,
)

from zospy.api.stubs._ZOSAPI.Analysis.Tolerancing import QuickYield

__all__ = (
    "QuickYield",
    "IAS_ISOElementDrawing",
    "IAS_QuickYield",
    "IAS_TolerancingHistogram",
    "IAS_TolerancingYield",
    "ITolerancingOperand",
    "ITolerancingOperands",
    "QYCompensations",
    "QYCompensatorStrategy",
    "QYPrecisions",
    "ShowAsISO",
)

class IAS_ISOElementDrawing(IAS_):
    @property
    def Surface(self) -> IAS_Surface: ...
    @property
    def ShowAs(self) -> ShowAsISO: ...
    @ShowAs.setter
    def ShowAs(self, value: ShowAsISO) -> None: ...
    def ExportISODrawingImage(self, Filepath: str) -> bool: ...
    def ExportISOXML(self, file: str) -> bool: ...
    def ImportAllFromLDE(self) -> None: ...
    def ImportFromTDE(self) -> None: ...
    def Reset(self) -> None: ...

class IAS_QuickYield(IAS_):
    @property
    def Field(self) -> IAS_Field: ...
    @property
    def Wavelength(self) -> IAS_Wavelength: ...
    @property
    def Configuration(self) -> int: ...
    @Configuration.setter
    def Configuration(self, value: int) -> None: ...
    @property
    def NumMonteCarlo(self) -> int: ...
    @NumMonteCarlo.setter
    def NumMonteCarlo(self, value: int) -> None: ...
    @property
    def PupilSampling(self) -> int: ...
    @PupilSampling.setter
    def PupilSampling(self, value: int) -> None: ...
    @property
    def Statistic(self) -> MonteCarloStatistics: ...
    @Statistic.setter
    def Statistic(self, value: MonteCarloStatistics) -> None: ...
    @property
    def Precision(self) -> QYPrecisions: ...
    @Precision.setter
    def Precision(self, value: QYPrecisions) -> None: ...
    @property
    def Compensation(self) -> QYCompensations: ...
    @Compensation.setter
    def Compensation(self, value: QYCompensations) -> None: ...
    @property
    def QYField(self) -> IAS_QYField: ...
    @property
    def CompensatorStrategy(self) -> QYCompensatorStrategy: ...
    @CompensatorStrategy.setter
    def CompensatorStrategy(self, value: QYCompensatorStrategy) -> None: ...

class IAS_TolerancingHistogram(IAS_):
    @property
    def Filename(self) -> str: ...
    @Filename.setter
    def Filename(self, value: str) -> None: ...
    @property
    def Operand(self) -> int: ...
    @Operand.setter
    def Operand(self, value: int) -> None: ...
    @property
    def MinValue(self) -> float: ...
    @MinValue.setter
    def MinValue(self, value: float) -> None: ...
    @property
    def MaxValue(self) -> float: ...
    @MaxValue.setter
    def MaxValue(self, value: float) -> None: ...
    @property
    def NumBins(self) -> int: ...
    @NumBins.setter
    def NumBins(self, value: int) -> None: ...
    def GetOperands(self) -> ITolerancingOperands: ...
    def GetToleranceFiles(self) -> list[str]: ...
    def UseSystemTolerances(self) -> None: ...

class IAS_TolerancingYield(IAS_):
    @property
    def Filename(self) -> str: ...
    @Filename.setter
    def Filename(self, value: str) -> None: ...
    @property
    def Operand(self) -> int: ...
    @Operand.setter
    def Operand(self, value: int) -> None: ...
    def GetOperands(self) -> ITolerancingOperands: ...
    def GetToleranceFiles(self) -> list[str]: ...
    def UseSystemTolerances(self) -> None: ...

class ITolerancingOperand:
    @property
    def OperandName(self) -> str: ...
    @property
    def ParameterData(self) -> str: ...

class ITolerancingOperands:
    @property
    def NumberOfOperands(self) -> int: ...
    @property
    def Operands(self) -> list[ITolerancingOperand]: ...
    def GetOperand(self, operandIndex: int) -> ITolerancingOperand: ...

# QYCompensations is imported as constant

# QYCompensatorStrategy is imported as constant

# QYPrecisions is imported as constant

# ShowAsISO is imported as constant
