"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "FftPsfType",
    "PsfRotation",
    "PsfSampling",
)

class FftPsfType:
    Linear: FftPsfType = ...
    Log: FftPsfType = ...
    Phase: FftPsfType = ...
    Real: FftPsfType = ...
    Imaginary: FftPsfType = ...

class PsfRotation:
    CW0: PsfRotation = ...
    CW90: PsfRotation = ...
    CW180: PsfRotation = ...
    CW270: PsfRotation = ...

class PsfSampling:
    PsfS_32x32: PsfSampling = ...
    PsfS_64x64: PsfSampling = ...
    PsfS_128x128: PsfSampling = ...
    PsfS_256x256: PsfSampling = ...
    PsfS_512x512: PsfSampling = ...
    PsfS_1024x1024: PsfSampling = ...
    PsfS_2048x2048: PsfSampling = ...
    PsfS_4096x4096: PsfSampling = ...
    PsfS_8192x8192: PsfSampling = ...
    PsfS_16384x16384: PsfSampling = ...
