"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "CoatingStatusType",
    "ConversionOrder",
    "CoordinateConversionResult",
    "CoordinateReturnType",
    "IndexDataType",
    "InterpolationMethod",
    "NodesDataType",
    "PilotRadiusMode",
    "PointCloudFileFormat",
    "PupilApodizationType",
    "QTypes",
    "STARDeformationOption",
    "SubstrateType",
    "SurfaceApertureTypes",
    "SurfaceColumn",
    "SurfaceEdgeDraw",
    "SurfaceScatteringTypes",
    "SurfaceType",
    "TiltDecenterOrderType",
    "TiltDecenterPickupType",
    "TiltType",
    "XYSampling",
)

class CoatingStatusType:
    Fixed: CoatingStatusType = ...
    Variable: CoatingStatusType = ...
    Pickup: CoatingStatusType = ...

class ConversionOrder:
    Forward: ConversionOrder = ...
    Reverse: ConversionOrder = ...

class CoordinateConversionResult:
    Success: CoordinateConversionResult = ...
    Error_MultiConfig: CoordinateConversionResult = ...
    Error_TiltDecenter: CoordinateConversionResult = ...
    Error_IgnoredSurface: CoordinateConversionResult = ...
    Error_CoordianteBreak: CoordinateConversionResult = ...
    Error_InvalidRange: CoordinateConversionResult = ...

class CoordinateReturnType:
    None_: CoordinateReturnType = ...
    OrientationOnly: CoordinateReturnType = ...
    OrientationXY: CoordinateReturnType = ...
    OrientationXYZ: CoordinateReturnType = ...

class IndexDataType:
    None_: IndexDataType = ...
    PhysicsBasedIndex: IndexDataType = ...
    DirectRefractiveIndex: IndexDataType = ...
    Unknown: IndexDataType = ...

class InterpolationMethod:
    BicubicSpline: InterpolationMethod = ...
    Linear: InterpolationMethod = ...

class NodesDataType:
    SurfaceDeformationNoRBM: NodesDataType = ...
    RefractiveIndex: NodesDataType = ...
    TemperatureAndRefractiveIndex: NodesDataType = ...
    SurfaceDeformation: NodesDataType = ...

class PilotRadiusMode:
    BestFit: PilotRadiusMode = ...
    Shorter: PilotRadiusMode = ...
    Longer: PilotRadiusMode = ...
    X: PilotRadiusMode = ...
    Y: PilotRadiusMode = ...
    Plane: PilotRadiusMode = ...
    User: PilotRadiusMode = ...

class PointCloudFileFormat:
    ASCII: PointCloudFileFormat = ...
    Binary: PointCloudFileFormat = ...
    CompressedBinary: PointCloudFileFormat = ...

class PupilApodizationType:
    None_: PupilApodizationType = ...
    Gaussian: PupilApodizationType = ...
    Tangential: PupilApodizationType = ...

class QTypes:
    Qbfs: QTypes = ...
    Qcon: QTypes = ...

class STARDeformationOption:
    DeformationWithRBMs: STARDeformationOption = ...
    DeformationWithoutRBMs: STARDeformationOption = ...
    OnlyRBMs: STARDeformationOption = ...
    NoDeformation: STARDeformationOption = ...

class SubstrateType:
    None_: SubstrateType = ...
    Flat: SubstrateType = ...
    Curved: SubstrateType = ...

class SurfaceApertureTypes:
    None_: SurfaceApertureTypes = ...
    CircularAperture: SurfaceApertureTypes = ...
    CircularObscuration: SurfaceApertureTypes = ...
    Spider: SurfaceApertureTypes = ...
    RectangularAperture: SurfaceApertureTypes = ...
    RectangularObscuration: SurfaceApertureTypes = ...
    EllipticalAperture: SurfaceApertureTypes = ...
    EllipticalObscuration: SurfaceApertureTypes = ...
    UserAperture: SurfaceApertureTypes = ...
    UserObscuration: SurfaceApertureTypes = ...
    FloatingAperture: SurfaceApertureTypes = ...

class SurfaceColumn:
    Comment: SurfaceColumn = ...
    Radius: SurfaceColumn = ...
    Thickness: SurfaceColumn = ...
    Material: SurfaceColumn = ...
    Coating: SurfaceColumn = ...
    SemiDiameter: SurfaceColumn = ...
    ChipZone: SurfaceColumn = ...
    MechanicalSemiDiameter: SurfaceColumn = ...
    Conic: SurfaceColumn = ...
    TCE: SurfaceColumn = ...
    Par0: SurfaceColumn = ...
    Par1: SurfaceColumn = ...
    Par2: SurfaceColumn = ...
    Par3: SurfaceColumn = ...
    Par4: SurfaceColumn = ...
    Par5: SurfaceColumn = ...
    Par6: SurfaceColumn = ...
    Par7: SurfaceColumn = ...
    Par8: SurfaceColumn = ...
    Par9: SurfaceColumn = ...
    Par10: SurfaceColumn = ...
    Par11: SurfaceColumn = ...
    Par12: SurfaceColumn = ...
    Par13: SurfaceColumn = ...
    Par14: SurfaceColumn = ...
    Par15: SurfaceColumn = ...
    Par16: SurfaceColumn = ...
    Par17: SurfaceColumn = ...
    Par18: SurfaceColumn = ...
    Par19: SurfaceColumn = ...
    Par20: SurfaceColumn = ...
    Par21: SurfaceColumn = ...
    Par22: SurfaceColumn = ...
    Par23: SurfaceColumn = ...
    Par24: SurfaceColumn = ...
    Par25: SurfaceColumn = ...
    Par26: SurfaceColumn = ...
    Par27: SurfaceColumn = ...
    Par28: SurfaceColumn = ...
    Par29: SurfaceColumn = ...
    Par30: SurfaceColumn = ...
    Par31: SurfaceColumn = ...
    Par32: SurfaceColumn = ...
    Par33: SurfaceColumn = ...
    Par34: SurfaceColumn = ...
    Par35: SurfaceColumn = ...
    Par36: SurfaceColumn = ...
    Par37: SurfaceColumn = ...
    Par38: SurfaceColumn = ...
    Par39: SurfaceColumn = ...
    Par40: SurfaceColumn = ...
    Par41: SurfaceColumn = ...
    Par42: SurfaceColumn = ...
    Par43: SurfaceColumn = ...
    Par44: SurfaceColumn = ...
    Par45: SurfaceColumn = ...
    Par46: SurfaceColumn = ...
    Par47: SurfaceColumn = ...
    Par48: SurfaceColumn = ...
    Par49: SurfaceColumn = ...
    Par50: SurfaceColumn = ...
    Par51: SurfaceColumn = ...
    Par52: SurfaceColumn = ...
    Par53: SurfaceColumn = ...
    Par54: SurfaceColumn = ...
    Par55: SurfaceColumn = ...
    Par56: SurfaceColumn = ...
    Par57: SurfaceColumn = ...
    Par58: SurfaceColumn = ...
    Par59: SurfaceColumn = ...
    Par60: SurfaceColumn = ...
    Par61: SurfaceColumn = ...
    Par62: SurfaceColumn = ...
    Par63: SurfaceColumn = ...
    Par64: SurfaceColumn = ...
    Par65: SurfaceColumn = ...
    Par66: SurfaceColumn = ...
    Par67: SurfaceColumn = ...
    Par68: SurfaceColumn = ...
    Par69: SurfaceColumn = ...
    Par70: SurfaceColumn = ...
    Par71: SurfaceColumn = ...
    Par72: SurfaceColumn = ...
    Par73: SurfaceColumn = ...
    Par74: SurfaceColumn = ...
    Par75: SurfaceColumn = ...
    Par76: SurfaceColumn = ...
    Par77: SurfaceColumn = ...
    Par78: SurfaceColumn = ...
    Par79: SurfaceColumn = ...
    Par80: SurfaceColumn = ...
    Par81: SurfaceColumn = ...
    Par82: SurfaceColumn = ...
    Par83: SurfaceColumn = ...
    Par84: SurfaceColumn = ...
    Par85: SurfaceColumn = ...
    Par86: SurfaceColumn = ...
    Par87: SurfaceColumn = ...
    Par88: SurfaceColumn = ...
    Par89: SurfaceColumn = ...
    Par90: SurfaceColumn = ...
    Par91: SurfaceColumn = ...
    Par92: SurfaceColumn = ...
    Par93: SurfaceColumn = ...
    Par94: SurfaceColumn = ...
    Par95: SurfaceColumn = ...
    Par96: SurfaceColumn = ...
    Par97: SurfaceColumn = ...
    Par98: SurfaceColumn = ...
    Par99: SurfaceColumn = ...
    Par100: SurfaceColumn = ...
    Par101: SurfaceColumn = ...
    Par102: SurfaceColumn = ...
    Par103: SurfaceColumn = ...
    Par104: SurfaceColumn = ...
    Par105: SurfaceColumn = ...
    Par106: SurfaceColumn = ...
    Par107: SurfaceColumn = ...
    Par108: SurfaceColumn = ...
    Par109: SurfaceColumn = ...
    Par110: SurfaceColumn = ...
    Par111: SurfaceColumn = ...
    Par112: SurfaceColumn = ...
    Par113: SurfaceColumn = ...
    Par114: SurfaceColumn = ...
    Par115: SurfaceColumn = ...
    Par116: SurfaceColumn = ...
    Par117: SurfaceColumn = ...
    Par118: SurfaceColumn = ...
    Par119: SurfaceColumn = ...
    Par120: SurfaceColumn = ...
    Par121: SurfaceColumn = ...
    Par122: SurfaceColumn = ...
    Par123: SurfaceColumn = ...
    Par124: SurfaceColumn = ...
    Par125: SurfaceColumn = ...
    Par126: SurfaceColumn = ...
    Par127: SurfaceColumn = ...
    Par128: SurfaceColumn = ...
    Par129: SurfaceColumn = ...
    Par130: SurfaceColumn = ...
    Par131: SurfaceColumn = ...
    Par132: SurfaceColumn = ...
    Par133: SurfaceColumn = ...
    Par134: SurfaceColumn = ...
    Par135: SurfaceColumn = ...
    Par136: SurfaceColumn = ...
    Par137: SurfaceColumn = ...
    Par138: SurfaceColumn = ...
    Par139: SurfaceColumn = ...
    Par140: SurfaceColumn = ...
    Par141: SurfaceColumn = ...
    Par142: SurfaceColumn = ...
    Par143: SurfaceColumn = ...
    Par144: SurfaceColumn = ...
    Par145: SurfaceColumn = ...
    Par146: SurfaceColumn = ...
    Par147: SurfaceColumn = ...
    Par148: SurfaceColumn = ...
    Par149: SurfaceColumn = ...
    Par150: SurfaceColumn = ...
    Par151: SurfaceColumn = ...
    Par152: SurfaceColumn = ...
    Par153: SurfaceColumn = ...
    Par154: SurfaceColumn = ...
    Par155: SurfaceColumn = ...
    Par156: SurfaceColumn = ...
    Par157: SurfaceColumn = ...
    Par158: SurfaceColumn = ...
    Par159: SurfaceColumn = ...
    Par160: SurfaceColumn = ...
    Par161: SurfaceColumn = ...
    Par162: SurfaceColumn = ...
    Par163: SurfaceColumn = ...
    Par164: SurfaceColumn = ...
    Par165: SurfaceColumn = ...
    Par166: SurfaceColumn = ...
    Par167: SurfaceColumn = ...
    Par168: SurfaceColumn = ...
    Par169: SurfaceColumn = ...
    Par170: SurfaceColumn = ...
    Par171: SurfaceColumn = ...
    Par172: SurfaceColumn = ...
    Par173: SurfaceColumn = ...
    Par174: SurfaceColumn = ...
    Par175: SurfaceColumn = ...
    Par176: SurfaceColumn = ...
    Par177: SurfaceColumn = ...
    Par178: SurfaceColumn = ...
    Par179: SurfaceColumn = ...
    Par180: SurfaceColumn = ...
    Par181: SurfaceColumn = ...
    Par182: SurfaceColumn = ...
    Par183: SurfaceColumn = ...
    Par184: SurfaceColumn = ...
    Par185: SurfaceColumn = ...
    Par186: SurfaceColumn = ...
    Par187: SurfaceColumn = ...
    Par188: SurfaceColumn = ...
    Par189: SurfaceColumn = ...
    Par190: SurfaceColumn = ...
    Par191: SurfaceColumn = ...
    Par192: SurfaceColumn = ...
    Par193: SurfaceColumn = ...
    Par194: SurfaceColumn = ...
    Par195: SurfaceColumn = ...
    Par196: SurfaceColumn = ...
    Par197: SurfaceColumn = ...
    Par198: SurfaceColumn = ...
    Par199: SurfaceColumn = ...
    Par200: SurfaceColumn = ...
    Par201: SurfaceColumn = ...
    Par202: SurfaceColumn = ...
    Par203: SurfaceColumn = ...
    Par204: SurfaceColumn = ...
    Par205: SurfaceColumn = ...
    Par206: SurfaceColumn = ...
    Par207: SurfaceColumn = ...
    Par208: SurfaceColumn = ...
    Par209: SurfaceColumn = ...
    Par210: SurfaceColumn = ...
    Par211: SurfaceColumn = ...
    Par212: SurfaceColumn = ...
    Par213: SurfaceColumn = ...
    Par214: SurfaceColumn = ...
    Par215: SurfaceColumn = ...
    Par216: SurfaceColumn = ...
    Par217: SurfaceColumn = ...
    Par218: SurfaceColumn = ...
    Par219: SurfaceColumn = ...
    Par220: SurfaceColumn = ...
    Par221: SurfaceColumn = ...
    Par222: SurfaceColumn = ...
    Par223: SurfaceColumn = ...
    Par224: SurfaceColumn = ...
    Par225: SurfaceColumn = ...
    Par226: SurfaceColumn = ...
    Par227: SurfaceColumn = ...
    Par228: SurfaceColumn = ...
    Par229: SurfaceColumn = ...
    Par230: SurfaceColumn = ...
    Par231: SurfaceColumn = ...
    Par232: SurfaceColumn = ...
    Par233: SurfaceColumn = ...
    Par234: SurfaceColumn = ...
    Par235: SurfaceColumn = ...
    Par236: SurfaceColumn = ...
    Par237: SurfaceColumn = ...
    Par238: SurfaceColumn = ...
    Par239: SurfaceColumn = ...
    Par240: SurfaceColumn = ...
    Par241: SurfaceColumn = ...
    Par242: SurfaceColumn = ...
    Par243: SurfaceColumn = ...
    Par244: SurfaceColumn = ...
    Par245: SurfaceColumn = ...
    Par246: SurfaceColumn = ...
    Par247: SurfaceColumn = ...
    Par248: SurfaceColumn = ...
    Par249: SurfaceColumn = ...
    Par250: SurfaceColumn = ...
    Par251: SurfaceColumn = ...
    Par252: SurfaceColumn = ...
    Par253: SurfaceColumn = ...
    Par254: SurfaceColumn = ...

class SurfaceEdgeDraw:
    Squared: SurfaceEdgeDraw = ...
    Tapered: SurfaceEdgeDraw = ...
    Flat: SurfaceEdgeDraw = ...

class SurfaceScatteringTypes:
    None_: SurfaceScatteringTypes = ...
    Lambertian: SurfaceScatteringTypes = ...
    Gaussian: SurfaceScatteringTypes = ...
    ABg: SurfaceScatteringTypes = ...
    ABgFile: SurfaceScatteringTypes = ...
    BSDF: SurfaceScatteringTypes = ...
    User: SurfaceScatteringTypes = ...
    ISScatterCatalog: SurfaceScatteringTypes = ...

class SurfaceType:
    ABCD: SurfaceType = ...
    AlternateEven: SurfaceType = ...
    AlternateOdd: SurfaceType = ...
    AnnularZernikeSag: SurfaceType = ...
    Atmospheric: SurfaceType = ...
    Biconic: SurfaceType = ...
    BiconicZernike: SurfaceType = ...
    Binary1: SurfaceType = ...
    Binary2: SurfaceType = ...
    Binary3: SurfaceType = ...
    Binary4: SurfaceType = ...
    BirefringentIn: SurfaceType = ...
    BirefringentOut: SurfaceType = ...
    BlackBoxLens: SurfaceType = ...
    ChebyShv: SurfaceType = ...
    Conjugate: SurfaceType = ...
    CoordinateBreak: SurfaceType = ...
    CubicSpline: SurfaceType = ...
    CylinderFrensel: SurfaceType = ...
    CylinderFresnel: SurfaceType = ...
    Data: SurfaceType = ...
    DiffractionGrating: SurfaceType = ...
    EllipticalGrating1: SurfaceType = ...
    EllipticalGrating2: SurfaceType = ...
    EvenAspheric: SurfaceType = ...
    ExtendedToroidalGrating: SurfaceType = ...
    ExtendedAsphere: SurfaceType = ...
    ExtendedCubicSpline: SurfaceType = ...
    ExtendedFresnel: SurfaceType = ...
    ExtendedOddAsphere: SurfaceType = ...
    ExtendedPolynomial: SurfaceType = ...
    Fresnel: SurfaceType = ...
    GeneralizedFresnel: SurfaceType = ...
    Gradient1: SurfaceType = ...
    Gradient2: SurfaceType = ...
    Gradient3: SurfaceType = ...
    Gradient4: SurfaceType = ...
    Gradient5: SurfaceType = ...
    Gradient6: SurfaceType = ...
    Gradient7: SurfaceType = ...
    Gradient9: SurfaceType = ...
    Gradient10: SurfaceType = ...
    Gradient12: SurfaceType = ...
    Gradium: SurfaceType = ...
    GridGradient: SurfaceType = ...
    GridPhase: SurfaceType = ...
    GridSag: SurfaceType = ...
    Hologram1: SurfaceType = ...
    Hologram2: SurfaceType = ...
    Irregular: SurfaceType = ...
    JonesMatrix: SurfaceType = ...
    NonSequential: SurfaceType = ...
    OddAsphere: SurfaceType = ...
    OddCosine: SurfaceType = ...
    OffAxisConicFreeform: SurfaceType = ...
    OpticallyFabricatedHologram: SurfaceType = ...
    Paraxial: SurfaceType = ...
    ParaxialXY: SurfaceType = ...
    Periodic: SurfaceType = ...
    Polynomial: SurfaceType = ...
    QTypeAsphere: SurfaceType = ...
    QTypeFreeform: SurfaceType = ...
    RadialGrating: SurfaceType = ...
    RadialNurbs: SurfaceType = ...
    RetroReflect: SurfaceType = ...
    SlideSurface: SurfaceType = ...
    Standard: SurfaceType = ...
    Superconic: SurfaceType = ...
    Tilted: SurfaceType = ...
    Toroidal: SurfaceType = ...
    ToroidalGrat: SurfaceType = ...
    ToroidalHologram: SurfaceType = ...
    ToroidalNurbs: SurfaceType = ...
    UserDefined: SurfaceType = ...
    VariableLineSpaceGrating: SurfaceType = ...
    ZernikeAnnularPhase: SurfaceType = ...
    ZernikeFringePhase: SurfaceType = ...
    ZernikeFringeSag: SurfaceType = ...
    ZernikeStandardPhase: SurfaceType = ...
    ZernikeStandardSag: SurfaceType = ...
    ZonePlate: SurfaceType = ...
    Freeform: SurfaceType = ...

class TiltDecenterOrderType:
    Decenter_Tilt: TiltDecenterOrderType = ...
    Tilt_Decenter: TiltDecenterOrderType = ...

class TiltDecenterPickupType:
    Explicit: TiltDecenterPickupType = ...
    PickupSurface: TiltDecenterPickupType = ...
    ReverseSurface: TiltDecenterPickupType = ...

class TiltType:
    XTilt: TiltType = ...
    YTilt: TiltType = ...

class XYSampling:
    S32: XYSampling = ...
    S64: XYSampling = ...
    S128: XYSampling = ...
    S256: XYSampling = ...
    S512: XYSampling = ...
    S1024: XYSampling = ...
    S2048: XYSampling = ...
    S4096: XYSampling = ...
    S8192: XYSampling = ...
    S16384: XYSampling = ...
