"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "BackgroundOptions",
    "BrightnessOptions",
    "CameraViewpointOptions",
    "ColorRaysByCrossSectionOptions",
    "ColorRaysByNSCOptions",
    "ColorRaysByOptions",
    "DetectorDisplayModeOptions",
    "DetectorPixelColorOptions",
    "DrawSectionOptions",
    "LineThicknessOptions",
    "NumberSegmentsOptions",
    "OpacityOptions",
    "RayTraceOptions",
    "RealPupilOptions",
)

class BackgroundOptions:
    White: BackgroundOptions = ...
    Black: BackgroundOptions = ...
    Red: BackgroundOptions = ...
    Green: BackgroundOptions = ...
    Blue: BackgroundOptions = ...
    DarkGreen: BackgroundOptions = ...
    DarkBlue: BackgroundOptions = ...
    Color01: BackgroundOptions = ...
    Color02: BackgroundOptions = ...
    Color03: BackgroundOptions = ...
    Color04: BackgroundOptions = ...
    Color05: BackgroundOptions = ...
    Color06: BackgroundOptions = ...
    Color07: BackgroundOptions = ...
    Color08: BackgroundOptions = ...
    Color09: BackgroundOptions = ...
    Color10: BackgroundOptions = ...
    Color11: BackgroundOptions = ...
    Color12: BackgroundOptions = ...
    Color13: BackgroundOptions = ...
    Color14: BackgroundOptions = ...
    Color15: BackgroundOptions = ...
    Color16: BackgroundOptions = ...
    Color17: BackgroundOptions = ...
    Color18: BackgroundOptions = ...
    Color19: BackgroundOptions = ...
    Color20: BackgroundOptions = ...
    Color21: BackgroundOptions = ...
    Color22: BackgroundOptions = ...
    Color23: BackgroundOptions = ...
    Color24: BackgroundOptions = ...
    Gradient01: BackgroundOptions = ...
    Gradient02: BackgroundOptions = ...
    Gradient03: BackgroundOptions = ...
    Gradient04: BackgroundOptions = ...
    Gradient05: BackgroundOptions = ...
    Gradient06: BackgroundOptions = ...
    Gradient07: BackgroundOptions = ...
    Gradient08: BackgroundOptions = ...
    Gradient09: BackgroundOptions = ...
    Gradient10: BackgroundOptions = ...
    GradientUser: BackgroundOptions = ...

class BrightnessOptions:
    P100: BrightnessOptions = ...
    P90: BrightnessOptions = ...
    P80: BrightnessOptions = ...
    P70: BrightnessOptions = ...
    P60: BrightnessOptions = ...
    P50: BrightnessOptions = ...
    P40: BrightnessOptions = ...
    P30: BrightnessOptions = ...
    P20: BrightnessOptions = ...
    P10: BrightnessOptions = ...

class CameraViewpointOptions:
    Isometric: CameraViewpointOptions = ...
    XY: CameraViewpointOptions = ...
    YZ: CameraViewpointOptions = ...
    XZ: CameraViewpointOptions = ...

class ColorRaysByCrossSectionOptions:
    Fields: ColorRaysByCrossSectionOptions = ...
    Waves: ColorRaysByCrossSectionOptions = ...
    Wavelength: ColorRaysByCrossSectionOptions = ...

class ColorRaysByNSCOptions:
    SourceNumber: ColorRaysByNSCOptions = ...
    WaveNumber: ColorRaysByNSCOptions = ...
    ConfigNumber: ColorRaysByNSCOptions = ...
    Wavelength: ColorRaysByNSCOptions = ...
    SegmentNumber: ColorRaysByNSCOptions = ...

class ColorRaysByOptions:
    Fields: ColorRaysByOptions = ...
    Waves: ColorRaysByOptions = ...
    Config: ColorRaysByOptions = ...
    Wavelength: ColorRaysByOptions = ...

class DetectorDisplayModeOptions:
    Consider: DetectorDisplayModeOptions = ...
    GreyScaleFlux: DetectorDisplayModeOptions = ...
    InverseGreyScaleFlux: DetectorDisplayModeOptions = ...
    FalseColorFlux: DetectorDisplayModeOptions = ...
    InverseFalseColorFlux: DetectorDisplayModeOptions = ...
    GreyScaleIrradiance: DetectorDisplayModeOptions = ...
    InverseGreyScaleIrradiance: DetectorDisplayModeOptions = ...
    FalseColorIrradiance: DetectorDisplayModeOptions = ...
    InverseFalseColorIrradiance: DetectorDisplayModeOptions = ...

class DetectorPixelColorOptions:
    DoNotColorIndividualPoints: DetectorPixelColorOptions = ...
    ByRaysOnLayout: DetectorPixelColorOptions = ...
    ByLastAnalysis: DetectorPixelColorOptions = ...

class DrawSectionOptions:
    P100: DrawSectionOptions = ...
    P75: DrawSectionOptions = ...
    P50: DrawSectionOptions = ...
    P25: DrawSectionOptions = ...

class LineThicknessOptions:
    Standard: LineThicknessOptions = ...
    Thick: LineThicknessOptions = ...
    Thickest: LineThicknessOptions = ...
    Thinnest: LineThicknessOptions = ...
    Thin: LineThicknessOptions = ...

class NumberSegmentsOptions:
    S_8: NumberSegmentsOptions = ...
    S_16: NumberSegmentsOptions = ...
    S_32: NumberSegmentsOptions = ...
    S_64: NumberSegmentsOptions = ...
    S_128: NumberSegmentsOptions = ...

class OpacityOptions:
    Ignore: OpacityOptions = ...
    Consider: OpacityOptions = ...
    All50Percent: OpacityOptions = ...

class RayTraceOptions:
    UseRays: RayTraceOptions = ...
    LightningTraceTrueColor: RayTraceOptions = ...
    LightningTraceAvgWavelength: RayTraceOptions = ...

class RealPupilOptions:
    Pupils_Off: RealPupilOptions = ...
    Pupils_4: RealPupilOptions = ...
    Pupils_8: RealPupilOptions = ...
    Pupils_16: RealPupilOptions = ...
    Pupils_32: RealPupilOptions = ...
