"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "ToleranceColumn",
    "ToleranceOperandType",
)

class ToleranceColumn:
    Param1: ToleranceColumn = ...
    Param2: ToleranceColumn = ...
    Param3: ToleranceColumn = ...
    Nominal: ToleranceColumn = ...
    Min: ToleranceColumn = ...
    Max: ToleranceColumn = ...
    Comment: ToleranceColumn = ...

class ToleranceOperandType:
    TOFF: ToleranceOperandType = ...
    TRAD: ToleranceOperandType = ...
    TCUR: ToleranceOperandType = ...
    TFRN: ToleranceOperandType = ...
    TTHI: ToleranceOperandType = ...
    TCON: ToleranceOperandType = ...
    TSDI: ToleranceOperandType = ...
    TSDX: ToleranceOperandType = ...
    TSDY: ToleranceOperandType = ...
    TSDR: ToleranceOperandType = ...
    TSTX: ToleranceOperandType = ...
    TSTY: ToleranceOperandType = ...
    TIRX: ToleranceOperandType = ...
    TIRY: ToleranceOperandType = ...
    TIRR: ToleranceOperandType = ...
    TPAR: ToleranceOperandType = ...
    TEDV: ToleranceOperandType = ...
    TEDX: ToleranceOperandType = ...
    TEDY: ToleranceOperandType = ...
    TEDR: ToleranceOperandType = ...
    TETX: ToleranceOperandType = ...
    TETY: ToleranceOperandType = ...
    TETZ: ToleranceOperandType = ...
    TUDX: ToleranceOperandType = ...
    TUDY: ToleranceOperandType = ...
    TUTX: ToleranceOperandType = ...
    TUTY: ToleranceOperandType = ...
    TUTZ: ToleranceOperandType = ...
    TIND: ToleranceOperandType = ...
    TABB: ToleranceOperandType = ...
    TEXI: ToleranceOperandType = ...
    SAVE: ToleranceOperandType = ...
    COMP: ToleranceOperandType = ...
    CPAR: ToleranceOperandType = ...
    CEDV: ToleranceOperandType = ...
    CMCO: ToleranceOperandType = ...
    STAT: ToleranceOperandType = ...
    TWAV: ToleranceOperandType = ...
    TNPS: ToleranceOperandType = ...
    TNPA: ToleranceOperandType = ...
    TMCO: ToleranceOperandType = ...
    TEZI: ToleranceOperandType = ...
    TCMU: ToleranceOperandType = ...
    SEED: ToleranceOperandType = ...
    COMM: ToleranceOperandType = ...
    TPAI: ToleranceOperandType = ...
    TCIO: ToleranceOperandType = ...
    TCEO: ToleranceOperandType = ...
    TNMA: ToleranceOperandType = ...
    CNPA: ToleranceOperandType = ...
    CNPS: ToleranceOperandType = ...
    TRLX: ToleranceOperandType = ...
    TRLY: ToleranceOperandType = ...
    TRLR: ToleranceOperandType = ...
    TARX: ToleranceOperandType = ...
    TARY: ToleranceOperandType = ...
    TARR: ToleranceOperandType = ...
    ISOA: ToleranceOperandType = ...
    ISOB: ToleranceOperandType = ...
    ISOC: ToleranceOperandType = ...
    ISOD: ToleranceOperandType = ...
    MPVT: ToleranceOperandType = ...
