"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "FieldColumn",
    "FieldNormalizationType",
    "FieldPattern",
    "FieldType",
    "FNumberComputationType",
    "HuygensIntegralSettings",
    "ParaxialRaysSetting",
    "PolarizationMethod",
    "QuadratureSteps",
    "RayAimingMethod",
    "RayAimingType",
    "ReferenceOPDSetting",
    "WavelengthPreset",
    "ZemaxAfocalModeUnits",
    "ZemaxAnalysisUnits",
    "ZemaxApertureType",
    "ZemaxApodizationType",
    "ZemaxMTFUnits",
    "ZemaxSourceUnits",
    "ZemaxSystemUnits",
    "ZemaxUnitPrefix",
)

class FieldColumn:
    Comment: FieldColumn = ...
    X: FieldColumn = ...
    Y: FieldColumn = ...
    Weight: FieldColumn = ...
    VDX: FieldColumn = ...
    VDY: FieldColumn = ...
    VCX: FieldColumn = ...
    VCY: FieldColumn = ...
    TAN: FieldColumn = ...
    VAN: FieldColumn = ...

class FieldNormalizationType:
    Radial: FieldNormalizationType = ...
    Rectangular: FieldNormalizationType = ...

class FieldPattern:
    UniformY: FieldPattern = ...
    EqualAreaY: FieldPattern = ...
    UniformX: FieldPattern = ...
    EqualAreaX: FieldPattern = ...
    Grid: FieldPattern = ...
    UniformRadial: FieldPattern = ...
    EqualAreaRadial: FieldPattern = ...

class FieldType:
    Angle: FieldType = ...
    ObjectHeight: FieldType = ...
    ParaxialImageHeight: FieldType = ...
    RealImageHeight: FieldType = ...
    TheodoliteAngle: FieldType = ...

class FNumberComputationType:
    TracingRays: FNumberComputationType = ...
    PupilSizePosition: FNumberComputationType = ...

class HuygensIntegralSettings:
    Auto: HuygensIntegralSettings = ...
    Planar: HuygensIntegralSettings = ...
    Spherical: HuygensIntegralSettings = ...

class ParaxialRaysSetting:
    ConsiderCoordinateBreaks: ParaxialRaysSetting = ...
    IgnoreCoordinateBreaks: ParaxialRaysSetting = ...

class PolarizationMethod:
    XAxisMethod: PolarizationMethod = ...
    YAxisMethod: PolarizationMethod = ...
    ZAxisMethod: PolarizationMethod = ...

class QuadratureSteps:
    S2: QuadratureSteps = ...
    S4: QuadratureSteps = ...
    S6: QuadratureSteps = ...
    S8: QuadratureSteps = ...
    S10: QuadratureSteps = ...
    S12: QuadratureSteps = ...

class RayAimingMethod:
    Off: RayAimingMethod = ...
    Paraxial: RayAimingMethod = ...
    Real: RayAimingMethod = ...

class RayAimingType:
    Heuristic: RayAimingType = ...
    Optimize: RayAimingType = ...

class ReferenceOPDSetting:
    Absolute: ReferenceOPDSetting = ...
    Infinity: ReferenceOPDSetting = ...
    ExitPupil: ReferenceOPDSetting = ...
    Absolute2: ReferenceOPDSetting = ...

class WavelengthPreset:
    FdC_Visible: WavelengthPreset = ...
    Photopic_Bright: WavelengthPreset = ...
    Scotopic_Dark: WavelengthPreset = ...
    HeNe_0p6328: WavelengthPreset = ...
    HeNe_0p5438: WavelengthPreset = ...
    Argon_0p4880: WavelengthPreset = ...
    Argon_0p5145: WavelengthPreset = ...
    NDYAG_1p0641: WavelengthPreset = ...
    NDGlass_1p054: WavelengthPreset = ...
    CO2_10p60: WavelengthPreset = ...
    CrLiSAF_0p840: WavelengthPreset = ...
    TiAl203_0p760: WavelengthPreset = ...
    Ruby_0p6943: WavelengthPreset = ...
    HeCadmium_0p4416: WavelengthPreset = ...
    HeCadmium_0p3536: WavelengthPreset = ...
    HeCadmium_0p3250: WavelengthPreset = ...
    t_1p014: WavelengthPreset = ...
    r_0p707: WavelengthPreset = ...
    C_0p656: WavelengthPreset = ...
    d_0p587: WavelengthPreset = ...
    F_0p486: WavelengthPreset = ...
    g_0p436: WavelengthPreset = ...
    i_0p365: WavelengthPreset = ...
    Fp_0p365: WavelengthPreset = ...
    e_0p54607: WavelengthPreset = ...
    Cp_0p6438469: WavelengthPreset = ...
    FpeCp_Visible: WavelengthPreset = ...
    THz_193p10: WavelengthPreset = ...

class ZemaxAfocalModeUnits:
    Microradians: ZemaxAfocalModeUnits = ...
    Milliradians: ZemaxAfocalModeUnits = ...
    Radians: ZemaxAfocalModeUnits = ...
    ArcSeconds: ZemaxAfocalModeUnits = ...
    ArcMinutes: ZemaxAfocalModeUnits = ...
    Degrees: ZemaxAfocalModeUnits = ...

class ZemaxAnalysisUnits:
    WattsPerMMSq: ZemaxAnalysisUnits = ...
    WattsPerCMSq: ZemaxAnalysisUnits = ...
    WattsPerinSq: ZemaxAnalysisUnits = ...
    WattsPerMSq: ZemaxAnalysisUnits = ...
    WattsPerftSq: ZemaxAnalysisUnits = ...

class ZemaxApertureType:
    EntrancePupilDiameter: ZemaxApertureType = ...
    ImageSpaceFNum: ZemaxApertureType = ...
    ObjectSpaceNA: ZemaxApertureType = ...
    FloatByStopSize: ZemaxApertureType = ...
    ParaxialWorkingFNum: ZemaxApertureType = ...
    ObjectConeAngle: ZemaxApertureType = ...

class ZemaxApodizationType:
    Uniform: ZemaxApodizationType = ...
    Gaussian: ZemaxApodizationType = ...
    CosineCubed: ZemaxApodizationType = ...

class ZemaxMTFUnits:
    CyclesPerMillimeter: ZemaxMTFUnits = ...
    CyclesPerMilliradian: ZemaxMTFUnits = ...

class ZemaxSourceUnits:
    Watts: ZemaxSourceUnits = ...
    Lumens: ZemaxSourceUnits = ...
    Joules: ZemaxSourceUnits = ...

class ZemaxSystemUnits:
    Millimeters: ZemaxSystemUnits = ...
    Centimeters: ZemaxSystemUnits = ...
    Inches: ZemaxSystemUnits = ...
    Meters: ZemaxSystemUnits = ...

class ZemaxUnitPrefix:
    Femto: ZemaxUnitPrefix = ...
    Pico: ZemaxUnitPrefix = ...
    Nano: ZemaxUnitPrefix = ...
    Micro: ZemaxUnitPrefix = ...
    Milli: ZemaxUnitPrefix = ...
    None_: ZemaxUnitPrefix = ...
    Kilo: ZemaxUnitPrefix = ...
    Mega: ZemaxUnitPrefix = ...
    Giga: ZemaxUnitPrefix = ...
    Tera: ZemaxUnitPrefix = ...
