"""
This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

from __future__ import annotations

from zospy.api._ZOSAPI.Analysis.Settings import IAS_

__all__ = ("IAS_PathAnalysis", "PathAnalysisSortType")

class IAS_PathAnalysis(IAS_):
    @property
    def AvailableRayDatabaseFiles(self) -> list[str]: ...
    @property
    def FilterString(self) -> str: ...
    @property
    def FirstRay(self) -> int: ...
    @property
    def GeneratePathFilters(self) -> bool: ...
    @property
    def LastRay(self) -> int: ...
    @property
    def RayDatabaseFile(self) -> str: ...
    @property
    def RelativeMinimumFlux(self) -> float: ...
    @property
    def SortBy(self) -> PathAnalysisSortType: ...
    @FilterString.setter
    def FilterString(self, value: str) -> None: ...
    @FirstRay.setter
    def FirstRay(self, value: int) -> None: ...
    @GeneratePathFilters.setter
    def GeneratePathFilters(self, value: bool) -> None: ...
    @LastRay.setter
    def LastRay(self, value: int) -> None: ...
    @RayDatabaseFile.setter
    def RayDatabaseFile(self, value: str) -> None: ...
    @RelativeMinimumFlux.setter
    def RelativeMinimumFlux(self, value: float) -> None: ...
    @SortBy.setter
    def SortBy(self, value: PathAnalysisSortType) -> None: ...

class PathAnalysisSortType:
    TotalEndingFlux = 0
    NumberOfObjectsStruck = 1
    NumberOfBranches = 2
    LastObjectStruck = 3
    NumberOfUniqueObjectsStruct = 4
