"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = ("PathAnalysisSortType",)

class PathAnalysisSortType:
    TotalEndingFlux: PathAnalysisSortType = ...
    NumberOfObjectsStruck: PathAnalysisSortType = ...
    NumberOfBranches: PathAnalysisSortType = ...
    LastObjectStruck: PathAnalysisSortType = ...
    NumberOfUniqueObjectsStruct: PathAnalysisSortType = ...
    AverageOpticalPathLength: PathAnalysisSortType = ...
    NumberOfDiffractionEvents: PathAnalysisSortType = ...
