"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

from zospy.api.stubs._ZOSAPI_constants.Analysis.Tolerancing import QuickYield

__all__ = (
    "QuickYield",
    "QYCompensations",
    "QYCompensatorStrategy",
    "QYPrecisions",
    "ShowAsISO",
)

class QYCompensations:
    Standard: QYCompensations = ...
    High: QYCompensations = ...
    VeryHigh: QYCompensations = ...

class QYCompensatorStrategy:
    OptimizeAllDampedLeastSquares: QYCompensatorStrategy = ...
    ParaxialFocus: QYCompensatorStrategy = ...
    Ignore: QYCompensatorStrategy = ...
    OptimizeAllOrthogonalDescent: QYCompensatorStrategy = ...

class QYPrecisions:
    Standard: QYPrecisions = ...
    High: QYPrecisions = ...
    VeryHigh: QYPrecisions = ...

class ShowAsISO:
    Surface: ShowAsISO = ...
    Singlet: ShowAsISO = ...
    Doublet: ShowAsISO = ...
