"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

from zospy.api.stubs._ZOSAPI_constants import (
    Analysis,
    Common,
    Editors,
    Preferences,
    SystemData,
    Tools,
    Wizards,
)

__all__ = (
    "Analysis",
    "Common",
    "Editors",
    "Preferences",
    "SystemData",
    "Tools",
    "Wizards",
    "LensUpdateMode",
    "LicenseStatusType",
    "SessionModes",
    "STARUpdateMode",
    "SystemType",
    "UpdateStatus",
    "ZOSAPI_Mode",
)

class LensUpdateMode:
    None_: LensUpdateMode = ...
    EditorsOnly: LensUpdateMode = ...
    AllWindows: LensUpdateMode = ...

class LicenseStatusType:
    Unknown: LicenseStatusType = ...
    KeyNotWorking: LicenseStatusType = ...
    NewLicenseNeeded: LicenseStatusType = ...
    StandardEdition: LicenseStatusType = ...
    ProfessionalEdition: LicenseStatusType = ...
    PremiumEdition: LicenseStatusType = ...
    TooManyInstances: LicenseStatusType = ...
    NotAuthorized: LicenseStatusType = ...
    KeyNotFound: LicenseStatusType = ...
    KeyExpired: LicenseStatusType = ...
    Timeout: LicenseStatusType = ...
    InstanceConflict: LicenseStatusType = ...
    OpticsViewer: LicenseStatusType = ...
    OpticStudioHPCEdition: LicenseStatusType = ...
    EnterpriseEdition: LicenseStatusType = ...
    StudentEdition: LicenseStatusType = ...

class SessionModes:
    FromPreferences: SessionModes = ...
    SessionOn: SessionModes = ...
    SessionOff: SessionModes = ...

class STARUpdateMode:
    Normal: STARUpdateMode = ...
    Suspended: STARUpdateMode = ...

class SystemType:
    Sequential: SystemType = ...
    NonSequential: SystemType = ...

class UpdateStatus:
    NotChecked: UpdateStatus = ...
    UpToDate: UpdateStatus = ...
    AvailableEligible: UpdateStatus = ...
    AvailableIneligible: UpdateStatus = ...
    CheckFailed: UpdateStatus = ...
    NotSupported: UpdateStatus = ...

class ZOSAPI_Mode:
    Server: ZOSAPI_Mode = ...
    Operand: ZOSAPI_Mode = ...
    Plugin: ZOSAPI_Mode = ...
    UserAnalysis: ZOSAPI_Mode = ...
    UserAnalysisSettings: ZOSAPI_Mode = ...
