"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "POPBeamTypes",
    "POPDataTypes",
    "POPFiberPositions",
    "POPFiberTypes",
    "POPProjectionTypes",
    "POPScaleTypes",
    "POPShowAsTypes",
    "POPZoomTypes",
)

class POPBeamTypes:
    GaussianWaist: POPBeamTypes = ...
    GaussianAngle: POPBeamTypes = ...
    GaussianSizeAngle: POPBeamTypes = ...
    TopHat: POPBeamTypes = ...
    File: POPBeamTypes = ...
    DLL: POPBeamTypes = ...
    Multimode: POPBeamTypes = ...
    AstigmaticGaussian: POPBeamTypes = ...

class POPDataTypes:
    Irradiance: POPDataTypes = ...
    EXIrradiance: POPDataTypes = ...
    EYIrradiance: POPDataTypes = ...
    Phase: POPDataTypes = ...
    EXPhase: POPDataTypes = ...
    EYPhase: POPDataTypes = ...
    TransferMagnitude: POPDataTypes = ...
    TransferPhase: POPDataTypes = ...

class POPFiberPositions:
    ChiefRay: POPFiberPositions = ...
    SurfaceVertex: POPFiberPositions = ...

class POPFiberTypes:
    GaussianWaist: POPFiberTypes = ...
    GaussianAngle: POPFiberTypes = ...
    GaussianSizeAngle: POPFiberTypes = ...
    TopHat: POPFiberTypes = ...
    File: POPFiberTypes = ...
    DLL: POPFiberTypes = ...
    AstigmaticGaussian: POPFiberTypes = ...

class POPProjectionTypes:
    AlongBeam: POPProjectionTypes = ...
    AlongNormal: POPProjectionTypes = ...
    AlongLocalZ: POPProjectionTypes = ...

class POPScaleTypes:
    Linear: POPScaleTypes = ...
    Log_Minus_5: POPScaleTypes = ...
    Log_Minus_10: POPScaleTypes = ...
    Log_Minus_15: POPScaleTypes = ...

class POPShowAsTypes:
    Surface: POPShowAsTypes = ...
    Contour: POPShowAsTypes = ...
    GrayScale: POPShowAsTypes = ...
    InverseGrayScale: POPShowAsTypes = ...
    FalseColor: POPShowAsTypes = ...
    InverseFalseColor: POPShowAsTypes = ...
    CrossX: POPShowAsTypes = ...
    CrossY: POPShowAsTypes = ...
    Encircled: POPShowAsTypes = ...
    Ensquared: POPShowAsTypes = ...
    EnslittedX: POPShowAsTypes = ...
    EnslittedY: POPShowAsTypes = ...

class POPZoomTypes:
    NoZoom: POPZoomTypes = ...
    X2: POPZoomTypes = ...
    X4: POPZoomTypes = ...
    X8: POPZoomTypes = ...
    X16: POPZoomTypes = ...
