"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "ConvertAsphereTypes",
    "FindBestAsphereTypes",
)

class ConvertAsphereTypes:
    EvenAsphere: ConvertAsphereTypes = ...
    ExtendedAsphere: ConvertAsphereTypes = ...
    QTypeAsphereType0: ConvertAsphereTypes = ...
    QTypeAsphereType1: ConvertAsphereTypes = ...

class FindBestAsphereTypes:
    Conic: FindBestAsphereTypes = ...
    Polynomial_4thOrder: FindBestAsphereTypes = ...
    Polynomial_6thOrder: FindBestAsphereTypes = ...
    Polynomial_8thOrder: FindBestAsphereTypes = ...
    Polynomial_10thOrder: FindBestAsphereTypes = ...
    Polynomial_12thOrder: FindBestAsphereTypes = ...
