"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "DataType",
    "FoucaultShowAs",
    "KnifeType",
    "Types",
)

class DataType:
    Computed: DataType = ...
    Reference: DataType = ...
    Difference: DataType = ...

class FoucaultShowAs:
    Surface: FoucaultShowAs = ...
    Contour: FoucaultShowAs = ...
    GreyScale: FoucaultShowAs = ...
    InverseGreyScale: FoucaultShowAs = ...
    FalseColor: FoucaultShowAs = ...
    InverseFalseColor: FoucaultShowAs = ...
    X_CrossSection: FoucaultShowAs = ...
    Y_CrossSection: FoucaultShowAs = ...

class KnifeType:
    Horiz_Above: KnifeType = ...
    Horiz_Below: KnifeType = ...
    Vert_Right: KnifeType = ...
    Vert_Left: KnifeType = ...

class Types:
    Linear: Types = ...
    Log_Minus_3: Types = ...
    Log_Minus_6: Types = ...
    Log_Minus_9: Types = ...
    Log_Minus_12: Types = ...
    Log_Minus_15: Types = ...
    Log_Minus_18: Types = ...
