"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

from zospy.api.stubs._ZOSAPI_constants.Tools import (
    FileManager,
    General,
    Layouts,
    Optimization,
    OptimizationTools,
    RayTrace,
    Tolerancing,
)

__all__ = (
    "FileManager",
    "General",
    "Layouts",
    "Optimization",
    "OptimizationTools",
    "RayTrace",
    "Tolerancing",
    "CriticalRayType",
    "HPCEnvironments",
    "HPCNodeSize",
    "HPCRunState",
    "MaterialFormulas",
    "MaterialStatuses",
    "RayPatternOption",
    "RunStatus",
    "VertexOrder",
)

class CriticalRayType:
    Chief: CriticalRayType = ...
    Marginal: CriticalRayType = ...
    Grid: CriticalRayType = ...
    Ring: CriticalRayType = ...
    Y_Fan: CriticalRayType = ...
    X_Fan: CriticalRayType = ...
    XY_Fan: CriticalRayType = ...
    List: CriticalRayType = ...

class HPCEnvironments:
    OnPremise: HPCEnvironments = ...
    AWSKubernetes: HPCEnvironments = ...
    AzureKubernetes: HPCEnvironments = ...

class HPCNodeSize:
    Default: HPCNodeSize = ...
    Tiny: HPCNodeSize = ...
    Small: HPCNodeSize = ...
    Medium: HPCNodeSize = ...
    Large: HPCNodeSize = ...
    XLarge: HPCNodeSize = ...

class HPCRunState:
    NotRunning: HPCRunState = ...
    Initializing: HPCRunState = ...
    ClusterAllocating: HPCRunState = ...
    UploadingData: HPCRunState = ...
    Queued: HPCRunState = ...
    RunStarting: HPCRunState = ...
    WaitingForResults: HPCRunState = ...
    Complete: HPCRunState = ...

class MaterialFormulas:
    Schott: MaterialFormulas = ...
    Sellmeier1: MaterialFormulas = ...
    Herzberger: MaterialFormulas = ...
    Sellmeier2: MaterialFormulas = ...
    Conrady: MaterialFormulas = ...
    Sellmeier3: MaterialFormulas = ...
    Handbook1: MaterialFormulas = ...
    Handbook2: MaterialFormulas = ...
    Sellmeier4: MaterialFormulas = ...
    Extended: MaterialFormulas = ...
    Sellmeier5: MaterialFormulas = ...
    Extended2: MaterialFormulas = ...
    Extended3: MaterialFormulas = ...

class MaterialStatuses:
    Standard: MaterialStatuses = ...
    Preferred: MaterialStatuses = ...
    Obsolete: MaterialStatuses = ...
    Special: MaterialStatuses = ...
    Melt: MaterialStatuses = ...

class RayPatternOption:
    XyFan: RayPatternOption = ...
    XFan: RayPatternOption = ...
    YFan: RayPatternOption = ...
    ChiefAndRing: RayPatternOption = ...
    List: RayPatternOption = ...
    Grid: RayPatternOption = ...
    ChiefAndMarginals: RayPatternOption = ...

class RunStatus:
    Completed: RunStatus = ...
    FailedToStart: RunStatus = ...
    TimedOut: RunStatus = ...
    InvalidTimeout: RunStatus = ...

class VertexOrder:
    First: VertexOrder = ...
    Second: VertexOrder = ...
    Third: VertexOrder = ...
