"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "FileSource",
    "KnownFolder",
    "Operation",
)

class FileSource:
    Project: FileSource = ...
    Root: FileSource = ...
    Unknown: FileSource = ...

class KnownFolder:
    Project: KnownFolder = ...
    ABgData: KnownFolder = ...
    BlackBoxes: KnownFolder = ...
    Coatings: KnownFolder = ...
    Configs: KnownFolder = ...
    DllBulkScatter: KnownFolder = ...
    DllDiffractive: KnownFolder = ...
    DllGradientIndex: KnownFolder = ...
    DllObjects: KnownFolder = ...
    DllPhysicalOptics: KnownFolder = ...
    DllSources: KnownFolder = ...
    DllSurfaceScatter: KnownFolder = ...
    DllSurfaces: KnownFolder = ...
    Extend: KnownFolder = ...
    GlassCat: KnownFolder = ...
    ImaFiles: KnownFolder = ...
    Macros: KnownFolder = ...
    MeritFunction: KnownFolder = ...
    Miscellaneous: KnownFolder = ...
    ObjectsApertures: KnownFolder = ...
    ObjectsCadFiles: KnownFolder = ...
    ObjectsCreoParametricFiles: KnownFolder = ...
    ObjectsGridFiles: KnownFolder = ...
    ObjectsInventorFiles: KnownFolder = ...
    ObjectsPartDesignerObjects: KnownFolder = ...
    ObjectsPhosphorsAndFluorescenceFiles: KnownFolder = ...
    ObjectsPolygonObjects: KnownFolder = ...
    ObjectsStopFiles: KnownFolder = ...
    ObjectsSolidWorksFiles: KnownFolder = ...
    ObjectsSourcesEulumdat: KnownFolder = ...
    ObjectsSourcesIesna: KnownFolder = ...
    ObjectsSourcesRadiantSourceModelFiles: KnownFolder = ...
    ObjectsSourcesSourceFiles: KnownFolder = ...
    ObjectsSourcesSpectrumFiles: KnownFolder = ...
    ObjectsTabulatedObjects: KnownFolder = ...
    PopBeamFiles: KnownFolder = ...
    Profiles: KnownFolder = ...
    ScatterData: KnownFolder = ...
    Tolerance: KnownFolder = ...
    Udo: KnownFolder = ...
    ZosApiExtensions: KnownFolder = ...
    ZosApiOperands: KnownFolder = ...
    ZosApiUserAnalysis: KnownFolder = ...
    DllBirefringence: KnownFolder = ...
    Unknown: KnownFolder = ...

class Operation:
    None_: Operation = ...
    GetFilesInUse: Operation = ...
    GetAdditionalFiles: Operation = ...
