"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "EncircledEnergyTypes",
    "ExtendedSourceTypes",
    "GeometricLineEdgeSpreadTypes",
    "ReferToTypes",
)

class EncircledEnergyTypes:
    Encircled: EncircledEnergyTypes = ...
    X_Only: EncircledEnergyTypes = ...
    Y_Only: EncircledEnergyTypes = ...
    Ensquared: EncircledEnergyTypes = ...

class ExtendedSourceTypes:
    Encircled: ExtendedSourceTypes = ...
    X_Only: ExtendedSourceTypes = ...
    Y_Only: ExtendedSourceTypes = ...
    Ensquared: ExtendedSourceTypes = ...
    X_Distrib: ExtendedSourceTypes = ...
    Y_Distrib: ExtendedSourceTypes = ...

class GeometricLineEdgeSpreadTypes:
    LineEdge: GeometricLineEdgeSpreadTypes = ...
    Line: GeometricLineEdgeSpreadTypes = ...
    Edge: GeometricLineEdgeSpreadTypes = ...

class ReferToTypes:
    ChiefRay: ReferToTypes = ...
    Centroid: ReferToTypes = ...
    Vertex: ReferToTypes = ...
