"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "NSCSagRemoveOptions",
    "NSCSagShowAs",
)

class NSCSagRemoveOptions:
    None_: NSCSagRemoveOptions = ...
    BaseROC: NSCSagRemoveOptions = ...
    BestFitSphere: NSCSagRemoveOptions = ...
    AverageSag: NSCSagRemoveOptions = ...
    MinimumSag: NSCSagRemoveOptions = ...

class NSCSagShowAs:
    Surface: NSCSagShowAs = ...
    Contour: NSCSagShowAs = ...
    GreyScale: NSCSagShowAs = ...
    InverseGreyScale: NSCSagShowAs = ...
    FalseColor: NSCSagShowAs = ...
    InverseFalseColor: NSCSagShowAs = ...
    X_CrossSection: NSCSagShowAs = ...
    Y_CrossSection: NSCSagShowAs = ...
