"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "ApertureShapes",
    "ArrayMode",
    "BirefringentMode",
    "BirefringentReflections",
    "DetectorDataType",
    "DetectorShowAsType",
    "DiffractionSplitType",
    "DiffractiveFaceChoices",
    "DrawingResolutionType",
    "EfficiencySpectrumType",
    "EndCapOptions",
    "FaceIsType",
    "HologramTypes",
    "InterpolateChoices",
    "NCEIndexType",
    "ObjectColumn",
    "ObjectScatteringTypes",
    "ObjectType",
    "OrderChoices",
    "PixelAddressing",
    "PolarDetectorDataType",
    "RaysIgnoreObjectType",
    "RayTraceModes",
    "ScatterToType",
    "ShapeChoices",
    "SourceBulkScatterMode",
    "SourceColorMode",
    "SourceSamplingMethod",
    "UniformAngleChoices",
    "VolumePhysicsModelType",
)

class ApertureShapes:
    Annular: ApertureShapes = ...
    Elliptical: ApertureShapes = ...
    Rectangular: ApertureShapes = ...
    CyliderWithRectangular: ApertureShapes = ...

class ArrayMode:
    None_: ArrayMode = ...
    Rectangular: ArrayMode = ...
    Circular: ArrayMode = ...
    Hexapolar: ArrayMode = ...
    Hexagonal: ArrayMode = ...

class BirefringentMode:
    TraceOrdinayAndExtraordinary: BirefringentMode = ...
    TraceOrdinaryOnly: BirefringentMode = ...
    TraceExtraordinaryOnly: BirefringentMode = ...
    Waveplate: BirefringentMode = ...

class BirefringentReflections:
    TraceReflectedAndRefracted: BirefringentReflections = ...
    TraceRefractedOnly: BirefringentReflections = ...
    TraceReflectedOnly: BirefringentReflections = ...

class DetectorDataType:
    Real: DetectorDataType = ...
    Imaginary: DetectorDataType = ...
    Amplitude: DetectorDataType = ...
    Power: DetectorDataType = ...

class DetectorShowAsType:
    GreyScaleFlux: DetectorShowAsType = ...
    InverseGreyScaleFlux: DetectorShowAsType = ...
    FalseColorFlux: DetectorShowAsType = ...
    InverseFalseColorFlux: DetectorShowAsType = ...
    GreyScaleIrradiance: DetectorShowAsType = ...
    InverseGreyScaleIrradiance: DetectorShowAsType = ...
    FalseColorIrradiance: DetectorShowAsType = ...
    InverseFalseColorIrradiance: DetectorShowAsType = ...

class DiffractionSplitType:
    DontSplitByOrder: DiffractionSplitType = ...
    SplitByTable: DiffractionSplitType = ...
    SplitByDLL: DiffractionSplitType = ...

class DiffractiveFaceChoices:
    FrontFace: DiffractiveFaceChoices = ...
    BackFace: DiffractiveFaceChoices = ...

class DrawingResolutionType:
    Standard: DrawingResolutionType = ...
    Medium: DrawingResolutionType = ...
    High: DrawingResolutionType = ...
    Presentation: DrawingResolutionType = ...
    Custom: DrawingResolutionType = ...

class EfficiencySpectrumType:
    QuantumYield: EfficiencySpectrumType = ...
    Excitation: EfficiencySpectrumType = ...

class EndCapOptions:
    None_: EndCapOptions = ...
    First: EndCapOptions = ...
    Second: EndCapOptions = ...
    Both: EndCapOptions = ...

class FaceIsType:
    ObjectDefault: FaceIsType = ...
    Reflective: FaceIsType = ...
    Absorbing: FaceIsType = ...

class HologramTypes:
    Type_1: HologramTypes = ...
    Type_2: HologramTypes = ...

class InterpolateChoices:
    Bicubic: InterpolateChoices = ...
    Linear: InterpolateChoices = ...

class NCEIndexType:
    Isotropic: NCEIndexType = ...
    Birefringent: NCEIndexType = ...
    GRIN: NCEIndexType = ...

class ObjectColumn:
    Comment: ObjectColumn = ...
    RefObject: ObjectColumn = ...
    InsideOf: ObjectColumn = ...
    XPosition: ObjectColumn = ...
    YPosition: ObjectColumn = ...
    ZPosition: ObjectColumn = ...
    TiltX: ObjectColumn = ...
    TiltY: ObjectColumn = ...
    TiltZ: ObjectColumn = ...
    Material: ObjectColumn = ...
    Par1: ObjectColumn = ...
    Par2: ObjectColumn = ...
    Par3: ObjectColumn = ...
    Par4: ObjectColumn = ...
    Par5: ObjectColumn = ...
    Par6: ObjectColumn = ...
    Par7: ObjectColumn = ...
    Par8: ObjectColumn = ...
    Par9: ObjectColumn = ...
    Par10: ObjectColumn = ...
    Par11: ObjectColumn = ...
    Par12: ObjectColumn = ...
    Par13: ObjectColumn = ...
    Par14: ObjectColumn = ...
    Par15: ObjectColumn = ...
    Par16: ObjectColumn = ...
    Par17: ObjectColumn = ...
    Par18: ObjectColumn = ...
    Par19: ObjectColumn = ...
    Par20: ObjectColumn = ...
    Par21: ObjectColumn = ...
    Par22: ObjectColumn = ...
    Par23: ObjectColumn = ...
    Par24: ObjectColumn = ...
    Par25: ObjectColumn = ...
    Par26: ObjectColumn = ...
    Par27: ObjectColumn = ...
    Par28: ObjectColumn = ...
    Par29: ObjectColumn = ...
    Par30: ObjectColumn = ...
    Par31: ObjectColumn = ...
    Par32: ObjectColumn = ...
    Par33: ObjectColumn = ...
    Par34: ObjectColumn = ...
    Par35: ObjectColumn = ...
    Par36: ObjectColumn = ...
    Par37: ObjectColumn = ...
    Par38: ObjectColumn = ...
    Par39: ObjectColumn = ...
    Par40: ObjectColumn = ...
    Par41: ObjectColumn = ...
    Par42: ObjectColumn = ...
    Par43: ObjectColumn = ...
    Par44: ObjectColumn = ...
    Par45: ObjectColumn = ...
    Par46: ObjectColumn = ...
    Par47: ObjectColumn = ...
    Par48: ObjectColumn = ...
    Par49: ObjectColumn = ...
    Par50: ObjectColumn = ...
    Par51: ObjectColumn = ...
    Par52: ObjectColumn = ...
    Par53: ObjectColumn = ...
    Par54: ObjectColumn = ...
    Par55: ObjectColumn = ...
    Par56: ObjectColumn = ...
    Par57: ObjectColumn = ...
    Par58: ObjectColumn = ...
    Par59: ObjectColumn = ...
    Par60: ObjectColumn = ...
    Par61: ObjectColumn = ...
    Par62: ObjectColumn = ...
    Par63: ObjectColumn = ...
    Par64: ObjectColumn = ...
    Par65: ObjectColumn = ...
    Par66: ObjectColumn = ...
    Par67: ObjectColumn = ...
    Par68: ObjectColumn = ...
    Par69: ObjectColumn = ...
    Par70: ObjectColumn = ...
    Par71: ObjectColumn = ...
    Par72: ObjectColumn = ...
    Par73: ObjectColumn = ...
    Par74: ObjectColumn = ...
    Par75: ObjectColumn = ...
    Par76: ObjectColumn = ...
    Par77: ObjectColumn = ...
    Par78: ObjectColumn = ...
    Par79: ObjectColumn = ...
    Par80: ObjectColumn = ...
    Par81: ObjectColumn = ...
    Par82: ObjectColumn = ...
    Par83: ObjectColumn = ...
    Par84: ObjectColumn = ...
    Par85: ObjectColumn = ...
    Par86: ObjectColumn = ...
    Par87: ObjectColumn = ...
    Par88: ObjectColumn = ...
    Par89: ObjectColumn = ...
    Par90: ObjectColumn = ...
    Par91: ObjectColumn = ...
    Par92: ObjectColumn = ...
    Par93: ObjectColumn = ...
    Par94: ObjectColumn = ...
    Par95: ObjectColumn = ...
    Par96: ObjectColumn = ...
    Par97: ObjectColumn = ...
    Par98: ObjectColumn = ...
    Par99: ObjectColumn = ...
    Par100: ObjectColumn = ...
    Par101: ObjectColumn = ...
    Par102: ObjectColumn = ...
    Par103: ObjectColumn = ...
    Par104: ObjectColumn = ...
    Par105: ObjectColumn = ...
    Par106: ObjectColumn = ...
    Par107: ObjectColumn = ...
    Par108: ObjectColumn = ...
    Par109: ObjectColumn = ...
    Par110: ObjectColumn = ...
    Par111: ObjectColumn = ...
    Par112: ObjectColumn = ...
    Par113: ObjectColumn = ...
    Par114: ObjectColumn = ...
    Par115: ObjectColumn = ...
    Par116: ObjectColumn = ...
    Par117: ObjectColumn = ...
    Par118: ObjectColumn = ...
    Par119: ObjectColumn = ...
    Par120: ObjectColumn = ...
    Par121: ObjectColumn = ...
    Par122: ObjectColumn = ...
    Par123: ObjectColumn = ...
    Par124: ObjectColumn = ...
    Par125: ObjectColumn = ...
    Par126: ObjectColumn = ...
    Par127: ObjectColumn = ...
    Par128: ObjectColumn = ...
    Par129: ObjectColumn = ...
    Par130: ObjectColumn = ...
    Par131: ObjectColumn = ...
    Par132: ObjectColumn = ...
    Par133: ObjectColumn = ...
    Par134: ObjectColumn = ...
    Par135: ObjectColumn = ...
    Par136: ObjectColumn = ...
    Par137: ObjectColumn = ...
    Par138: ObjectColumn = ...
    Par139: ObjectColumn = ...
    Par140: ObjectColumn = ...
    Par141: ObjectColumn = ...
    Par142: ObjectColumn = ...
    Par143: ObjectColumn = ...
    Par144: ObjectColumn = ...
    Par145: ObjectColumn = ...
    Par146: ObjectColumn = ...
    Par147: ObjectColumn = ...
    Par148: ObjectColumn = ...
    Par149: ObjectColumn = ...
    Par150: ObjectColumn = ...
    Par151: ObjectColumn = ...
    Par152: ObjectColumn = ...
    Par153: ObjectColumn = ...
    Par154: ObjectColumn = ...
    Par155: ObjectColumn = ...
    Par156: ObjectColumn = ...
    Par157: ObjectColumn = ...
    Par158: ObjectColumn = ...
    Par159: ObjectColumn = ...
    Par160: ObjectColumn = ...
    Par161: ObjectColumn = ...
    Par162: ObjectColumn = ...
    Par163: ObjectColumn = ...
    Par164: ObjectColumn = ...
    Par165: ObjectColumn = ...
    Par166: ObjectColumn = ...
    Par167: ObjectColumn = ...
    Par168: ObjectColumn = ...
    Par169: ObjectColumn = ...
    Par170: ObjectColumn = ...
    Par171: ObjectColumn = ...
    Par172: ObjectColumn = ...
    Par173: ObjectColumn = ...
    Par174: ObjectColumn = ...
    Par175: ObjectColumn = ...
    Par176: ObjectColumn = ...
    Par177: ObjectColumn = ...
    Par178: ObjectColumn = ...
    Par179: ObjectColumn = ...
    Par180: ObjectColumn = ...
    Par181: ObjectColumn = ...
    Par182: ObjectColumn = ...
    Par183: ObjectColumn = ...
    Par184: ObjectColumn = ...
    Par185: ObjectColumn = ...
    Par186: ObjectColumn = ...
    Par187: ObjectColumn = ...
    Par188: ObjectColumn = ...
    Par189: ObjectColumn = ...
    Par190: ObjectColumn = ...
    Par191: ObjectColumn = ...
    Par192: ObjectColumn = ...
    Par193: ObjectColumn = ...
    Par194: ObjectColumn = ...
    Par195: ObjectColumn = ...
    Par196: ObjectColumn = ...
    Par197: ObjectColumn = ...
    Par198: ObjectColumn = ...
    Par199: ObjectColumn = ...
    Par200: ObjectColumn = ...
    Par201: ObjectColumn = ...
    Par202: ObjectColumn = ...
    Par203: ObjectColumn = ...
    Par204: ObjectColumn = ...
    Par205: ObjectColumn = ...
    Par206: ObjectColumn = ...
    Par207: ObjectColumn = ...
    Par208: ObjectColumn = ...
    Par209: ObjectColumn = ...
    Par210: ObjectColumn = ...
    Par211: ObjectColumn = ...
    Par212: ObjectColumn = ...
    Par213: ObjectColumn = ...
    Par214: ObjectColumn = ...
    Par215: ObjectColumn = ...
    Par216: ObjectColumn = ...
    Par217: ObjectColumn = ...
    Par218: ObjectColumn = ...
    Par219: ObjectColumn = ...
    Par220: ObjectColumn = ...
    Par221: ObjectColumn = ...
    Par222: ObjectColumn = ...
    Par223: ObjectColumn = ...
    Par224: ObjectColumn = ...
    Par225: ObjectColumn = ...
    Par226: ObjectColumn = ...
    Par227: ObjectColumn = ...
    Par228: ObjectColumn = ...
    Par229: ObjectColumn = ...
    Par230: ObjectColumn = ...
    Par231: ObjectColumn = ...
    Par232: ObjectColumn = ...
    Par233: ObjectColumn = ...
    Par234: ObjectColumn = ...
    Par235: ObjectColumn = ...
    Par236: ObjectColumn = ...
    Par237: ObjectColumn = ...
    Par238: ObjectColumn = ...
    Par239: ObjectColumn = ...
    Par240: ObjectColumn = ...
    Par241: ObjectColumn = ...
    Par242: ObjectColumn = ...
    Par243: ObjectColumn = ...
    Par244: ObjectColumn = ...
    Par245: ObjectColumn = ...
    Par246: ObjectColumn = ...
    Par247: ObjectColumn = ...
    Par248: ObjectColumn = ...
    Par249: ObjectColumn = ...
    Par250: ObjectColumn = ...

class ObjectScatteringTypes:
    None_: ObjectScatteringTypes = ...
    Lambertian: ObjectScatteringTypes = ...
    Gaussian: ObjectScatteringTypes = ...
    ABg: ObjectScatteringTypes = ...
    ABgFile: ObjectScatteringTypes = ...
    BSDF: ObjectScatteringTypes = ...
    ISScatterCatalog: ObjectScatteringTypes = ...
    User: ObjectScatteringTypes = ...

class ObjectType:
    AnnularAsphericLens: ObjectType = ...
    AnnularAxialLens: ObjectType = ...
    AnnularVolume: ObjectType = ...
    Annulus: ObjectType = ...
    Array: ObjectType = ...
    ArrayRing: ObjectType = ...
    AsphericSurface: ObjectType = ...
    AsphericSurface2: ObjectType = ...
    AxiconSurface: ObjectType = ...
    BiconicLens: ObjectType = ...
    BiconicSurface: ObjectType = ...
    BiconicZernike: ObjectType = ...
    BiconicZernikeSurface: ObjectType = ...
    Binary1: ObjectType = ...
    Binary2: ObjectType = ...
    Binary2A: ObjectType = ...
    Boolean: ObjectType = ...
    BooleanCAD: ObjectType = ...
    CADAssemblyAutodeskInventor: ObjectType = ...
    CADAssemblyCreoParametric: ObjectType = ...
    CADAssemblySolidWorks: ObjectType = ...
    CADPartAutodeskInventor: ObjectType = ...
    CADPartCreoParametric: ObjectType = ...
    CADPartSolidWorks: ObjectType = ...
    CADPartSTEPIGESSAT: ObjectType = ...
    CADPartSTL: ObjectType = ...
    CADPartZPD: ObjectType = ...
    Cone: ObjectType = ...
    CPC: ObjectType = ...
    CPCRectangular: ObjectType = ...
    CylinderPipe: ObjectType = ...
    CylinderVolume: ObjectType = ...
    Cylinder2Pipe: ObjectType = ...
    Cylinder2Volume: ObjectType = ...
    DetectorColor: ObjectType = ...
    DetectorPolar: ObjectType = ...
    DetectorRectangle: ObjectType = ...
    DetectorSurface: ObjectType = ...
    DetectorVolume: ObjectType = ...
    DiffractionGrating: ObjectType = ...
    DualBEFSurface: ObjectType = ...
    Ellipse: ObjectType = ...
    EllipticalVolume: ObjectType = ...
    EvenAsphereLens: ObjectType = ...
    ExtendedOddAsphereLens: ObjectType = ...
    ExtendedPolynomialLens: ObjectType = ...
    ExtendedPolynomialSurface: ObjectType = ...
    Extruded: ObjectType = ...
    FacetedSurface: ObjectType = ...
    FreeformZ: ObjectType = ...
    Fresnel1: ObjectType = ...
    Fresnel2: ObjectType = ...
    GridSagLens: ObjectType = ...
    GridSagSurface: ObjectType = ...
    GridSagFrontBack: ObjectType = ...
    HexagonalLensletArray: ObjectType = ...
    HologramLens: ObjectType = ...
    HologramSurface: ObjectType = ...
    JonesMatrix: ObjectType = ...
    LensletArray1: ObjectType = ...
    LensletArray2: ObjectType = ...
    MEMS: ObjectType = ...
    NullObject: ObjectType = ...
    OddAsphereLens: ObjectType = ...
    ParaxialLens: ObjectType = ...
    PolygonObject: ObjectType = ...
    RayRotator: ObjectType = ...
    RectangularCorner: ObjectType = ...
    Rectangle: ObjectType = ...
    RectangularPipe: ObjectType = ...
    RectangularPipeGrating: ObjectType = ...
    RectangularRoof: ObjectType = ...
    RectangularTorusSurface: ObjectType = ...
    RectangularTorusVolume: ObjectType = ...
    RectangularVolume: ObjectType = ...
    RectangularVolumeGrating: ObjectType = ...
    ReverseRadianceDetector: ObjectType = ...
    ReverseRadianceTarget: ObjectType = ...
    Slide: ObjectType = ...
    SourceDiffractive: ObjectType = ...
    SourceDiode: ObjectType = ...
    SourceDLL: ObjectType = ...
    SourceEllipse: ObjectType = ...
    SourceEULUMDATFile: ObjectType = ...
    SourceFilament: ObjectType = ...
    SourceFile: ObjectType = ...
    SourceGaussian: ObjectType = ...
    SourceIESNAFile: ObjectType = ...
    SourceImported: ObjectType = ...
    SourceObject: ObjectType = ...
    SourcePoint: ObjectType = ...
    SourceRadial: ObjectType = ...
    SourceRay: ObjectType = ...
    SourceRectangle: ObjectType = ...
    SourceTube: ObjectType = ...
    SourceTwoAngle: ObjectType = ...
    SourceVolumeCylindrical: ObjectType = ...
    SourceVolumeElliptical: ObjectType = ...
    SourceVolumeRectangular: ObjectType = ...
    Sphere: ObjectType = ...
    StandardLens: ObjectType = ...
    StandardSurface: ObjectType = ...
    Swept: ObjectType = ...
    TabulatedFactedRadial: ObjectType = ...
    TabulatedFactedToroid: ObjectType = ...
    TabulatedFrenselRadial: ObjectType = ...
    ToroidalHologram: ObjectType = ...
    ToroidalLens: ObjectType = ...
    ToroidalSurface: ObjectType = ...
    ToroidalSurfaceOddASphere: ObjectType = ...
    TorusSurface: ObjectType = ...
    TorusVolume: ObjectType = ...
    TriangularCorner: ObjectType = ...
    Triangle: ObjectType = ...
    UserDefinedObject: ObjectType = ...
    WolterSurface: ObjectType = ...
    ZernikeSurface: ObjectType = ...
    BooleanNative: ObjectType = ...
    CompoundLens: ObjectType = ...
    QTypeAsphereSurface: ObjectType = ...
    OffAxisMirror: ObjectType = ...

class OrderChoices:
    Before: OrderChoices = ...
    After: OrderChoices = ...

class PixelAddressing:
    ByRow: PixelAddressing = ...
    ByColumn: PixelAddressing = ...
    Individually: PixelAddressing = ...

class PolarDetectorDataType:
    Power: PolarDetectorDataType = ...
    PowerSolidAngle: PolarDetectorDataType = ...
    Lumens: PolarDetectorDataType = ...
    LumensSolidAngle: PolarDetectorDataType = ...
    Cx: PolarDetectorDataType = ...
    Cy: PolarDetectorDataType = ...
    u_T: PolarDetectorDataType = ...
    u_V: PolarDetectorDataType = ...
    TriX: PolarDetectorDataType = ...
    TriY: PolarDetectorDataType = ...
    TriZ: PolarDetectorDataType = ...

class RaysIgnoreObjectType:
    Never: RaysIgnoreObjectType = ...
    Always: RaysIgnoreObjectType = ...
    OnLaunch: RaysIgnoreObjectType = ...

class RayTraceModes:
    Standard: RayTraceModes = ...
    Flat: RayTraceModes = ...
    Shaded: RayTraceModes = ...
    Kernel: RayTraceModes = ...

class ScatterToType:
    ScatterToList: ScatterToType = ...
    ImportanceSampling: ScatterToType = ...

class ShapeChoices:
    Rectangular: ShapeChoices = ...
    Elliptical: ShapeChoices = ...

class SourceBulkScatterMode:
    Many: SourceBulkScatterMode = ...
    Once: SourceBulkScatterMode = ...
    Never: SourceBulkScatterMode = ...

class SourceColorMode:
    SystemWavelengths: SourceColorMode = ...
    CIE1931Tristimulus: SourceColorMode = ...
    CIE1931Chromaticity: SourceColorMode = ...
    CIE1931RGB: SourceColorMode = ...
    UniformPowerSpectrum: SourceColorMode = ...
    D65White: SourceColorMode = ...
    ColorTemperature: SourceColorMode = ...
    BlackBodySpectrum: SourceColorMode = ...
    SpectrumFile: SourceColorMode = ...
    CIE1976: SourceColorMode = ...

class SourceSamplingMethod:
    Random: SourceSamplingMethod = ...
    Sobol: SourceSamplingMethod = ...

class UniformAngleChoices:
    UniformIrradiance: UniformAngleChoices = ...
    UniformInAngleSpace: UniformAngleChoices = ...

class VolumePhysicsModelType:
    None_: VolumePhysicsModelType = ...
    AngleScattering: VolumePhysicsModelType = ...
    DLLDefinedScattering: VolumePhysicsModelType = ...
    PhotoluminescenceModel: VolumePhysicsModelType = ...
