"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

from zospy.api.stubs._ZOSAPI_constants.Analysis import (
    PhysicalOptics,
    RayTracing,
    Settings,
    Tolerancing,
)

__all__ = (
    "PhysicalOptics",
    "RayTracing",
    "Settings",
    "Tolerancing",
    "AnalysisIDM",
    "Beam",
    "BestFitSphereOptions",
    "ColorPaletteType",
    "DetectorViewerShowAsTypes",
    "DetectorViewerShowDataTypes",
    "ErrorType",
    "GiaShowAsTypes",
    "GridPlotType",
    "HuygensShowAsTypes",
    "HuygensSurfaceMftShowAsTypes",
    "POPSampling",
    "RemoveOptions",
    "SampleSizes",
    "SampleSizes_ContrastLoss",
    "SampleSizes_Pow2Plus1",
    "SampleSizes_Pow2Plus1_X",
    "ShowAs",
    "SurfaceCurvatureCrossData",
    "SurfaceCurvatureData",
    "SurfacePhaseData",
    "SurfacePhaseSlopeCrossData",
    "SurfacePhaseSlopeData",
    "SurfaceSagData",
    "SurfaceSlopeCrossData",
    "SurfaceSlopeData",
    "UserAnalysisDataType",
)

class AnalysisIDM:
    RayFan: AnalysisIDM = ...
    OpticalPathFan: AnalysisIDM = ...
    PupilAberrationFan: AnalysisIDM = ...
    FieldCurvatureAndDistortion: AnalysisIDM = ...
    FocalShiftDiagram: AnalysisIDM = ...
    GridDistortion: AnalysisIDM = ...
    LateralColor: AnalysisIDM = ...
    LongitudinalAberration: AnalysisIDM = ...
    RayTrace: AnalysisIDM = ...
    SeidelCoefficients: AnalysisIDM = ...
    SeidelDiagram: AnalysisIDM = ...
    ZernikeAnnularCoefficients: AnalysisIDM = ...
    ZernikeCoefficientsVsField: AnalysisIDM = ...
    ZernikeFringeCoefficients: AnalysisIDM = ...
    ZernikeStandardCoefficients: AnalysisIDM = ...
    FftMtf: AnalysisIDM = ...
    FftThroughFocusMtf: AnalysisIDM = ...
    GeometricThroughFocusMtf: AnalysisIDM = ...
    GeometricMtf: AnalysisIDM = ...
    FftMtfMap: AnalysisIDM = ...
    GeometricMtfMap: AnalysisIDM = ...
    FftSurfaceMtf: AnalysisIDM = ...
    FftMtfvsField: AnalysisIDM = ...
    GeometricMtfvsField: AnalysisIDM = ...
    HuygensMtfvsField: AnalysisIDM = ...
    HuygensMtf: AnalysisIDM = ...
    HuygensSurfaceMtf: AnalysisIDM = ...
    HuygensThroughFocusMtf: AnalysisIDM = ...
    FftPsf: AnalysisIDM = ...
    FftPsfCrossSection: AnalysisIDM = ...
    FftPsfLineEdgeSpread: AnalysisIDM = ...
    HuygensPsfCrossSection: AnalysisIDM = ...
    HuygensPsf: AnalysisIDM = ...
    DiffractionEncircledEnergy: AnalysisIDM = ...
    GeometricEncircledEnergy: AnalysisIDM = ...
    GeometricLineEdgeSpread: AnalysisIDM = ...
    ExtendedSourceEncircledEnergy: AnalysisIDM = ...
    SurfaceCurvatureCross: AnalysisIDM = ...
    SurfacePhaseCross: AnalysisIDM = ...
    SurfaceSagCross: AnalysisIDM = ...
    SurfaceCurvature: AnalysisIDM = ...
    SurfacePhase: AnalysisIDM = ...
    SurfaceSag: AnalysisIDM = ...
    StandardSpot: AnalysisIDM = ...
    ThroughFocusSpot: AnalysisIDM = ...
    FullFieldSpot: AnalysisIDM = ...
    MatrixSpot: AnalysisIDM = ...
    ConfigurationMatrixSpot: AnalysisIDM = ...
    RMSField: AnalysisIDM = ...
    RMSFieldMap: AnalysisIDM = ...
    RMSLambdaDiagram: AnalysisIDM = ...
    RMSFocus: AnalysisIDM = ...
    Foucault: AnalysisIDM = ...
    Interferogram: AnalysisIDM = ...
    WavefrontMap: AnalysisIDM = ...
    DetectorViewer: AnalysisIDM = ...
    Draw2D: AnalysisIDM = ...
    Draw3D: AnalysisIDM = ...
    ImageSimulation: AnalysisIDM = ...
    GeometricImageAnalysis: AnalysisIDM = ...
    IMABIMFileViewer: AnalysisIDM = ...
    GeometricBitmapImageAnalysis: AnalysisIDM = ...
    BitmapFileViewer: AnalysisIDM = ...
    LightSourceAnalysis: AnalysisIDM = ...
    PartiallyCoherentImageAnalysis: AnalysisIDM = ...
    ExtendedDiffractionImageAnalysis: AnalysisIDM = ...
    BiocularFieldOfViewAnalysis: AnalysisIDM = ...
    BiocularDipvergenceConvergence: AnalysisIDM = ...
    RelativeIllumination: AnalysisIDM = ...
    VignettingDiagramSettings: AnalysisIDM = ...
    FootprintSettings: AnalysisIDM = ...
    YYbarDiagram: AnalysisIDM = ...
    PowerFieldMapSettings: AnalysisIDM = ...
    PowerPupilMapSettings: AnalysisIDM = ...
    IncidentAnglevsImageHeight: AnalysisIDM = ...
    FiberCouplingSettings: AnalysisIDM = ...
    YNIContributions: AnalysisIDM = ...
    SagTable: AnalysisIDM = ...
    CardinalPoints: AnalysisIDM = ...
    DispersionDiagram: AnalysisIDM = ...
    GlassMap: AnalysisIDM = ...
    AthermalGlassMap: AnalysisIDM = ...
    InternalTransmissionvsWavelength: AnalysisIDM = ...
    DispersionvsWavelength: AnalysisIDM = ...
    GrinProfile: AnalysisIDM = ...
    GradiumProfile: AnalysisIDM = ...
    UniversalPlot1D: AnalysisIDM = ...
    UniversalPlot2D: AnalysisIDM = ...
    PolarizationRayTrace: AnalysisIDM = ...
    PolarizationPupilMap: AnalysisIDM = ...
    Transmission: AnalysisIDM = ...
    PhaseAberration: AnalysisIDM = ...
    TransmissionFan: AnalysisIDM = ...
    ParaxialGaussianBeam: AnalysisIDM = ...
    SkewGaussianBeam: AnalysisIDM = ...
    PhysicalOpticsPropagation: AnalysisIDM = ...
    BeamFileViewer: AnalysisIDM = ...
    ReflectionvsAngle: AnalysisIDM = ...
    TransmissionvsAngle: AnalysisIDM = ...
    AbsorptionvsAngle: AnalysisIDM = ...
    DiattenuationvsAngle: AnalysisIDM = ...
    PhasevsAngle: AnalysisIDM = ...
    RetardancevsAngle: AnalysisIDM = ...
    ReflectionvsWavelength: AnalysisIDM = ...
    TransmissionvsWavelength: AnalysisIDM = ...
    AbsorptionvsWavelength: AnalysisIDM = ...
    DiattenuationvsWavelength: AnalysisIDM = ...
    PhasevsWavelength: AnalysisIDM = ...
    RetardancevsWavelength: AnalysisIDM = ...
    DirectivityPlot: AnalysisIDM = ...
    SourcePolarViewer: AnalysisIDM = ...
    PhotoluminscenceViewer: AnalysisIDM = ...
    SourceSpectrumViewer: AnalysisIDM = ...
    RadiantSourceModelViewerSettings: AnalysisIDM = ...
    SurfaceDataSettings: AnalysisIDM = ...
    PrescriptionDataSettings: AnalysisIDM = ...
    FileComparatorSettings: AnalysisIDM = ...
    PartViewer: AnalysisIDM = ...
    ReverseRadianceAnalysis: AnalysisIDM = ...
    PathAnalysis: AnalysisIDM = ...
    FluxvsWavelength: AnalysisIDM = ...
    RoadwayLighting: AnalysisIDM = ...
    SourceIlluminationMap: AnalysisIDM = ...
    ScatterFunctionViewer: AnalysisIDM = ...
    ScatterPolarPlotSettings: AnalysisIDM = ...
    ZemaxElementDrawing: AnalysisIDM = ...
    ShadedModel: AnalysisIDM = ...
    NSCShadedModel: AnalysisIDM = ...
    NSC3DLayout: AnalysisIDM = ...
    NSCObjectViewer: AnalysisIDM = ...
    RayDatabaseViewer: AnalysisIDM = ...
    ISOElementDrawing: AnalysisIDM = ...
    SystemData: AnalysisIDM = ...
    TestPlateList: AnalysisIDM = ...
    SourceColorChart1931: AnalysisIDM = ...
    SourceColorChart1976: AnalysisIDM = ...
    PrescriptionGraphic: AnalysisIDM = ...
    CriticalRayTracer: AnalysisIDM = ...
    ContrastLoss: AnalysisIDM = ...
    CoatingListing: AnalysisIDM = ...
    FullFieldAberration: AnalysisIDM = ...
    SurfaceSlope: AnalysisIDM = ...
    SurfaceSlopeCross: AnalysisIDM = ...
    QuickYield: AnalysisIDM = ...
    SystemCheck: AnalysisIDM = ...
    ToleranceYield: AnalysisIDM = ...
    ToleranceHistogram: AnalysisIDM = ...
    DiffEfficiency2D: AnalysisIDM = ...
    DiffEfficiencyAngular: AnalysisIDM = ...
    DiffEfficiencyChromatic: AnalysisIDM = ...
    NSCSurfaceSag: AnalysisIDM = ...
    NSCSingleRayTrace: AnalysisIDM = ...
    NSCGeometricMtf: AnalysisIDM = ...
    SurfacePhaseSlope: AnalysisIDM = ...
    SurfacePhaseSlopeCross: AnalysisIDM = ...
    STARAlignCheck: AnalysisIDM = ...
    STARSysViewer: AnalysisIDM = ...
    STAR2DDefPlot: AnalysisIDM = ...
    STARPerfChange: AnalysisIDM = ...
    STARIndexVsTemp: AnalysisIDM = ...
    STARInspectFEA: AnalysisIDM = ...
    UserDefinedCOM: AnalysisIDM = ...
    XXXTemplateXXX: AnalysisIDM = ...

class Beam:
    Reference: Beam = ...
    Configuration_1: Beam = ...
    Configuration_2: Beam = ...
    Configuration_3: Beam = ...
    Configuration_4: Beam = ...
    Configuration_5: Beam = ...
    Configuration_6: Beam = ...
    Configuration_7: Beam = ...
    Configuration_8: Beam = ...
    Configuration_9: Beam = ...
    Configuration_10: Beam = ...
    Configuration_11: Beam = ...
    Configuration_12: Beam = ...
    Configuration_13: Beam = ...
    Configuration_14: Beam = ...
    Configuration_15: Beam = ...
    Configuration_16: Beam = ...
    Configuration_17: Beam = ...
    Configuration_18: Beam = ...
    Configuration_19: Beam = ...
    Configuration_20: Beam = ...

class BestFitSphereOptions:
    MinimumVolume: BestFitSphereOptions = ...
    MinimumRMS: BestFitSphereOptions = ...
    MinimumRMSWithOffset: BestFitSphereOptions = ...

class ColorPaletteType:
    GreyScale: ColorPaletteType = ...
    FalseColor: ColorPaletteType = ...
    FalseColorOriginal: ColorPaletteType = ...
    Viridis: ColorPaletteType = ...
    Magma: ColorPaletteType = ...

class DetectorViewerShowAsTypes:
    GreyScale: DetectorViewerShowAsTypes = ...
    FullListing: DetectorViewerShowAsTypes = ...
    Text_CrossSection_Row: DetectorViewerShowAsTypes = ...
    AzimuthCrossSection: DetectorViewerShowAsTypes = ...
    GreyScale_Inverted: DetectorViewerShowAsTypes = ...
    Text_CrossSection_Column: DetectorViewerShowAsTypes = ...
    FalseColor: DetectorViewerShowAsTypes = ...
    FluxVsWaveLength: DetectorViewerShowAsTypes = ...
    FalseColor_Inverted: DetectorViewerShowAsTypes = ...
    TrueColor: DetectorViewerShowAsTypes = ...
    CrossSection_Row: DetectorViewerShowAsTypes = ...
    CrossSection: DetectorViewerShowAsTypes = ...
    Color_CrossSection_Row: DetectorViewerShowAsTypes = ...
    CrossSection_Column: DetectorViewerShowAsTypes = ...
    Directivity_Full: DetectorViewerShowAsTypes = ...
    Color_CrossSection_Column: DetectorViewerShowAsTypes = ...
    GeometricMtf: DetectorViewerShowAsTypes = ...
    Color_FluxVsWavelength: DetectorViewerShowAsTypes = ...
    Directivity_Half: DetectorViewerShowAsTypes = ...

class DetectorViewerShowDataTypes:
    IncoherentIrradiance: DetectorViewerShowDataTypes = ...
    Polar_AngleSpace: DetectorViewerShowDataTypes = ...
    IncoherentFluence: DetectorViewerShowDataTypes = ...
    IncidentFlux: DetectorViewerShowDataTypes = ...
    PositionSpace: DetectorViewerShowDataTypes = ...
    IncoherentIlluminance: DetectorViewerShowDataTypes = ...
    CoherentFluence: DetectorViewerShowDataTypes = ...
    AngleSpace: DetectorViewerShowDataTypes = ...
    CoherentIrradiance: DetectorViewerShowDataTypes = ...
    AbsorbedFlux: DetectorViewerShowDataTypes = ...
    CoherentIlluminance: DetectorViewerShowDataTypes = ...
    AbsorbedFluxVolume: DetectorViewerShowDataTypes = ...
    CoherentPhase: DetectorViewerShowDataTypes = ...
    RadiantIntensity: DetectorViewerShowDataTypes = ...
    LuminousIntensity: DetectorViewerShowDataTypes = ...
    LuminancePositionSpace: DetectorViewerShowDataTypes = ...
    RadiancePositionSpace: DetectorViewerShowDataTypes = ...
    LuminanceAngleSpace: DetectorViewerShowDataTypes = ...
    RadianceAngleSpace: DetectorViewerShowDataTypes = ...

class ErrorType:
    Success: ErrorType = ...
    InvalidParameter: ErrorType = ...
    InvalidSettings: ErrorType = ...
    Failed: ErrorType = ...
    AnalysisUnavailableForProgramMode: ErrorType = ...
    NotYetImplemented: ErrorType = ...
    NoSolverLicenseAvailable: ErrorType = ...
    ToolAlreadyOpen: ErrorType = ...
    SequentialOnly: ErrorType = ...
    NonSequentialOnly: ErrorType = ...
    SingleNSCRayTraceSupported: ErrorType = ...
    HPCNotAvailable: ErrorType = ...
    FeatureNotSupported: ErrorType = ...
    NotAvailableInLegacy: ErrorType = ...

class GiaShowAsTypes:
    Surface: GiaShowAsTypes = ...
    Contour: GiaShowAsTypes = ...
    GreyScale: GiaShowAsTypes = ...
    InverseGreyScale: GiaShowAsTypes = ...
    FalseColor: GiaShowAsTypes = ...
    InverseFalseColor: GiaShowAsTypes = ...
    SpotDiagram: GiaShowAsTypes = ...
    CrossX: GiaShowAsTypes = ...
    CrossY: GiaShowAsTypes = ...

class GridPlotType:
    Surface: GridPlotType = ...
    Contour: GridPlotType = ...
    GrayScale: GridPlotType = ...
    InverseGrayScale: GridPlotType = ...
    FalseColor: GridPlotType = ...
    InverseFalseColor: GridPlotType = ...

class HuygensShowAsTypes:
    Surface: HuygensShowAsTypes = ...
    Contour: HuygensShowAsTypes = ...
    GreyScale: HuygensShowAsTypes = ...
    InverseGreyScale: HuygensShowAsTypes = ...
    FalseColor: HuygensShowAsTypes = ...
    InverseFalseColor: HuygensShowAsTypes = ...
    TrueColor: HuygensShowAsTypes = ...

class HuygensSurfaceMftShowAsTypes:
    GreyScale: HuygensSurfaceMftShowAsTypes = ...
    InverseGreyScale: HuygensSurfaceMftShowAsTypes = ...
    FalseColor: HuygensSurfaceMftShowAsTypes = ...
    InverseFalseColor: HuygensSurfaceMftShowAsTypes = ...

class POPSampling:
    S_32: POPSampling = ...
    S_64: POPSampling = ...
    S_128: POPSampling = ...
    S_256: POPSampling = ...
    S_512: POPSampling = ...
    S_1024: POPSampling = ...
    S_1K: POPSampling = ...
    S_2048: POPSampling = ...
    S_2K: POPSampling = ...
    S_4K: POPSampling = ...
    S_4096: POPSampling = ...
    S_8192: POPSampling = ...
    S_8K: POPSampling = ...
    S_16384: POPSampling = ...
    S_16K: POPSampling = ...
    S_32K: POPSampling = ...
    S_32768: POPSampling = ...
    S_65536: POPSampling = ...
    S_64K: POPSampling = ...
    S_131072: POPSampling = ...
    S_128K: POPSampling = ...
    S_256K: POPSampling = ...
    S_262144: POPSampling = ...
    S_524288: POPSampling = ...
    S_512K: POPSampling = ...
    S_1048576: POPSampling = ...
    S_1M: POPSampling = ...
    S_2M: POPSampling = ...
    S_2097152: POPSampling = ...
    S_4194304: POPSampling = ...
    S_4M: POPSampling = ...
    S_8388608: POPSampling = ...
    S_8M: POPSampling = ...
    S_16M: POPSampling = ...
    S_16777216: POPSampling = ...
    S_33554432: POPSampling = ...
    S_32M: POPSampling = ...
    S_67108864: POPSampling = ...
    S_64M: POPSampling = ...
    S_128M: POPSampling = ...
    S_134217728: POPSampling = ...
    S_268435456: POPSampling = ...
    S_256M: POPSampling = ...
    S_536870912: POPSampling = ...
    S_512M: POPSampling = ...
    S_1073741824: POPSampling = ...
    S_1G: POPSampling = ...

class RemoveOptions:
    None_: RemoveOptions = ...
    BaseROC: RemoveOptions = ...
    BestFitSphere: RemoveOptions = ...
    BaseSag: RemoveOptions = ...
    CompositeSag: RemoveOptions = ...

class SampleSizes:
    S_32x32: SampleSizes = ...
    S_64x64: SampleSizes = ...
    S_128x128: SampleSizes = ...
    S_256x256: SampleSizes = ...
    S_512x512: SampleSizes = ...
    S_1024x1024: SampleSizes = ...
    S_2048x2048: SampleSizes = ...
    S_4096x4096: SampleSizes = ...
    S_8192x8192: SampleSizes = ...
    S_16384x16384: SampleSizes = ...

class SampleSizes_ContrastLoss:
    S_3x3: SampleSizes_ContrastLoss = ...
    S_5x5: SampleSizes_ContrastLoss = ...
    S_7x7: SampleSizes_ContrastLoss = ...
    S_9x9: SampleSizes_ContrastLoss = ...
    S_11x11: SampleSizes_ContrastLoss = ...
    S_13x13: SampleSizes_ContrastLoss = ...
    S_15x15: SampleSizes_ContrastLoss = ...
    S_17x17: SampleSizes_ContrastLoss = ...
    S_19x19: SampleSizes_ContrastLoss = ...
    S_21x21: SampleSizes_ContrastLoss = ...
    S_23x23: SampleSizes_ContrastLoss = ...
    S_25x25: SampleSizes_ContrastLoss = ...
    S_27x27: SampleSizes_ContrastLoss = ...
    S_29x29: SampleSizes_ContrastLoss = ...
    S_31x31: SampleSizes_ContrastLoss = ...
    S_33x33: SampleSizes_ContrastLoss = ...
    S_35x35: SampleSizes_ContrastLoss = ...
    S_37x37: SampleSizes_ContrastLoss = ...
    S_39x39: SampleSizes_ContrastLoss = ...
    S_41x41: SampleSizes_ContrastLoss = ...
    S_43x43: SampleSizes_ContrastLoss = ...
    S_45x45: SampleSizes_ContrastLoss = ...
    S_47x47: SampleSizes_ContrastLoss = ...
    S_49x49: SampleSizes_ContrastLoss = ...
    S_51x51: SampleSizes_ContrastLoss = ...
    S_53x53: SampleSizes_ContrastLoss = ...
    S_55x55: SampleSizes_ContrastLoss = ...
    S_57x57: SampleSizes_ContrastLoss = ...
    S_59x59: SampleSizes_ContrastLoss = ...
    S_61x61: SampleSizes_ContrastLoss = ...
    S_63x63: SampleSizes_ContrastLoss = ...
    S_65x65: SampleSizes_ContrastLoss = ...
    S_67x67: SampleSizes_ContrastLoss = ...
    S_69x69: SampleSizes_ContrastLoss = ...
    S_71x71: SampleSizes_ContrastLoss = ...
    S_73x73: SampleSizes_ContrastLoss = ...
    S_75x75: SampleSizes_ContrastLoss = ...
    S_77x77: SampleSizes_ContrastLoss = ...
    S_79x79: SampleSizes_ContrastLoss = ...
    S_81x81: SampleSizes_ContrastLoss = ...
    S_83x83: SampleSizes_ContrastLoss = ...

class SampleSizes_Pow2Plus1:
    S_33: SampleSizes_Pow2Plus1 = ...
    S_65: SampleSizes_Pow2Plus1 = ...
    S_129: SampleSizes_Pow2Plus1 = ...
    S_257: SampleSizes_Pow2Plus1 = ...
    S_513: SampleSizes_Pow2Plus1 = ...
    S_1025: SampleSizes_Pow2Plus1 = ...
    S_2049: SampleSizes_Pow2Plus1 = ...
    S_4097: SampleSizes_Pow2Plus1 = ...
    S_8193: SampleSizes_Pow2Plus1 = ...

class SampleSizes_Pow2Plus1_X:
    S_33x33: SampleSizes_Pow2Plus1_X = ...
    S_65x65: SampleSizes_Pow2Plus1_X = ...
    S_129x129: SampleSizes_Pow2Plus1_X = ...
    S_257x257: SampleSizes_Pow2Plus1_X = ...
    S_513x513: SampleSizes_Pow2Plus1_X = ...
    S_1025x1025: SampleSizes_Pow2Plus1_X = ...
    S_2049x2049: SampleSizes_Pow2Plus1_X = ...
    S_4097x4097: SampleSizes_Pow2Plus1_X = ...
    S_8193x8193: SampleSizes_Pow2Plus1_X = ...

class ShowAs:
    Surface: ShowAs = ...
    Contour: ShowAs = ...
    GreyScale: ShowAs = ...
    InverseGreyScale: ShowAs = ...
    FalseColor: ShowAs = ...
    InverseFalseColor: ShowAs = ...

class SurfaceCurvatureCrossData:
    TangentialCurvature: SurfaceCurvatureCrossData = ...
    SagittalCurvature: SurfaceCurvatureCrossData = ...
    X_Curvature: SurfaceCurvatureCrossData = ...
    Y_Curvature: SurfaceCurvatureCrossData = ...
    CurvatureModulus: SurfaceCurvatureCrossData = ...
    CurvatureUnused: SurfaceCurvatureCrossData = ...

class SurfaceCurvatureData:
    TangentialCurvature: SurfaceCurvatureData = ...
    SagittalCurvature: SurfaceCurvatureData = ...
    X_Curvature: SurfaceCurvatureData = ...
    Y_Curvature: SurfaceCurvatureData = ...
    CurvatureModulus: SurfaceCurvatureData = ...
    CurvatureUnused: SurfaceCurvatureData = ...

class SurfacePhaseData:
    SurfacePhase: SurfacePhaseData = ...

class SurfacePhaseSlopeCrossData:
    PhaseSlopeTangential: SurfacePhaseSlopeCrossData = ...
    PhaseSlopeSagittal: SurfacePhaseSlopeCrossData = ...
    PhaseSlopeX: SurfacePhaseSlopeCrossData = ...
    PhaseSlopeY: SurfacePhaseSlopeCrossData = ...
    PhaseSlopeModulus: SurfacePhaseSlopeCrossData = ...
    PhaseSlopeUnused: SurfacePhaseSlopeCrossData = ...

class SurfacePhaseSlopeData:
    PhaseSlopeTangential: SurfacePhaseSlopeData = ...
    PhaseSlopeSagittal: SurfacePhaseSlopeData = ...
    PhaseSlopeX: SurfacePhaseSlopeData = ...
    PhaseSlopeY: SurfacePhaseSlopeData = ...
    PhaseSlopeModulus: SurfacePhaseSlopeData = ...
    PhaseSlopeUnused: SurfacePhaseSlopeData = ...

class SurfaceSagData:
    SurfaceSag: SurfaceSagData = ...

class SurfaceSlopeCrossData:
    TangentialSlope: SurfaceSlopeCrossData = ...
    SagittalSlope: SurfaceSlopeCrossData = ...
    XSlope: SurfaceSlopeCrossData = ...
    YSlope: SurfaceSlopeCrossData = ...
    SlopeModulus: SurfaceSlopeCrossData = ...
    SlopeUnused: SurfaceSlopeCrossData = ...

class SurfaceSlopeData:
    SurfaceSlope: SurfaceSlopeData = ...
    TangentialSlope: SurfaceSlopeData = ...
    SagittalSlope: SurfaceSlopeData = ...
    XSlope: SurfaceSlopeData = ...
    YSlope: SurfaceSlopeData = ...
    SlopeModulus: SurfaceSlopeData = ...
    SlopeUnused: SurfaceSlopeData = ...

class UserAnalysisDataType:
    None_: UserAnalysisDataType = ...
    Line2D: UserAnalysisDataType = ...
    Grid: UserAnalysisDataType = ...
    GridRGB: UserAnalysisDataType = ...
    Text: UserAnalysisDataType = ...
