"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "CriterionTypes",
    "DefaultAndDegrees",
    "DefaultAndFringes",
    "OptimizationTypes",
    "PupilArmsCount",
    "ReferenceTypes",
    "ToleranceGrade",
    "ToleranceVendor",
    "WizardType",
)

class CriterionTypes:
    Wavefront: CriterionTypes = ...
    Contrast: CriterionTypes = ...
    Spot: CriterionTypes = ...
    Angular: CriterionTypes = ...

class DefaultAndDegrees:
    Default: DefaultAndDegrees = ...
    Degrees: DefaultAndDegrees = ...

class DefaultAndFringes:
    Default: DefaultAndFringes = ...
    Fringes: DefaultAndFringes = ...
    Percent: DefaultAndFringes = ...

class OptimizationTypes:
    RMS: OptimizationTypes = ...
    PTV: OptimizationTypes = ...

class PupilArmsCount:
    Arms_6: PupilArmsCount = ...
    Arms_8: PupilArmsCount = ...
    Arms_10: PupilArmsCount = ...
    Arms_12: PupilArmsCount = ...

class ReferenceTypes:
    Centroid: ReferenceTypes = ...
    ChiefRay: ReferenceTypes = ...
    Unreferenced: ReferenceTypes = ...

class ToleranceGrade:
    Commercial: ToleranceGrade = ...
    Precision: ToleranceGrade = ...
    HighPrecision: ToleranceGrade = ...
    CellPhoneLens: ToleranceGrade = ...

class ToleranceVendor:
    Asphericon: ToleranceVendor = ...
    EdmundOptics: ToleranceVendor = ...
    Generic: ToleranceVendor = ...
    LaCroix: ToleranceVendor = ...
    Optimax: ToleranceVendor = ...

class WizardType:
    NSCOptimization: WizardType = ...
    NSCBitmap: WizardType = ...
    NSCRoadwayLighting: WizardType = ...
    SEQOptimization: WizardType = ...
    NSCTolerance: WizardType = ...
    SEQTolerance: WizardType = ...
