"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "OptimizationAlgorithm",
    "OptimizationCycles",
    "OptimizationSaveCount",
)

class OptimizationAlgorithm:
    DampedLeastSquares: OptimizationAlgorithm = ...
    OrthogonalDescent: OptimizationAlgorithm = ...

class OptimizationCycles:
    Automatic: OptimizationCycles = ...
    Fixed_1_Cycle: OptimizationCycles = ...
    Fixed_5_Cycles: OptimizationCycles = ...
    Fixed_10_Cycles: OptimizationCycles = ...
    Fixed_50_Cycles: OptimizationCycles = ...
    Infinite: OptimizationCycles = ...

class OptimizationSaveCount:
    Save_10: OptimizationSaveCount = ...
    Save_20: OptimizationSaveCount = ...
    Save_30: OptimizationSaveCount = ...
    Save_40: OptimizationSaveCount = ...
    Save_50: OptimizationSaveCount = ...
    Save_60: OptimizationSaveCount = ...
    Save_70: OptimizationSaveCount = ...
    Save_80: OptimizationSaveCount = ...
    Save_90: OptimizationSaveCount = ...
    Save_100: OptimizationSaveCount = ...
