# builtins = [
#     "DateTime",
#     "SerializationInfo",
#     "StreamingContext",
#     "MemoryMappedFile",
#     "IntPtr",
#     "AsyncCallback",
#     "IAsyncResult",
#     "MethodInfo",
# ]

[lint]
select = ["E4", "E7", "E9", "F", "B", "PYI"]
ignore = ["E743", "F811", "PYI021"]