"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

__all__ = (
    "XYSymmetricField",
    "YSymmetricField",
)

class XYSymmetricField:
    All: XYSymmetricField = ...
    Zero: XYSymmetricField = ...
    YPositive70Percent: XYSymmetricField = ...
    YNegative70Percent: XYSymmetricField = ...
    YPositive100Percent: XYSymmetricField = ...
    YNegative100Percent: XYSymmetricField = ...
    XPositive70Percent: XYSymmetricField = ...
    XNegative70Percent: XYSymmetricField = ...
    XPositive100Percent: XYSymmetricField = ...
    XNegative100Percent: XYSymmetricField = ...

class YSymmetricField:
    All: YSymmetricField = ...
    Zero: YSymmetricField = ...
    Positive70Percent: YSymmetricField = ...
    Negative70Percent: YSymmetricField = ...
    Positive100Percent: YSymmetricField = ...
    Negative100Percent: YSymmetricField = ...
