"""This file provides autocompletions for the ZOS-API and was automatically generated.
It should not be edited manually.
"""

from __future__ import annotations

from zospy.api._ZOSAPI.Analysis.Settings import IAS_

__all__ = ("IAS_Fan", "SagittalAberrationComponent", "TangentialAberrationComponent")

class IAS_Fan(IAS_):
    @property
    def Field(self) -> IAS_Field: ...
    @property
    def Surface(self) -> IAS_Surface: ...
    @property
    def Wavelength(self) -> IAS_Wavelength: ...
    @property
    def NumberOfRays(self) -> int: ...
    @NumberOfRays.setter
    def NumberOfRays(self, value: int) -> None: ...
    @property
    def PlotScale(self) -> float: ...
    @PlotScale.setter
    def PlotScale(self, value: float) -> None: ...
    @property
    def CheckApertures(self) -> bool: ...
    @CheckApertures.setter
    def CheckApertures(self, value: bool) -> None: ...
    @property
    def VignettedPupil(self) -> bool: ...
    @VignettedPupil.setter
    def VignettedPupil(self, value: bool) -> None: ...
    @property
    def UseDashes(self) -> bool: ...
    @UseDashes.setter
    def UseDashes(self, value: bool) -> None: ...
    @property
    def Sagittal(self) -> SagittalAberrationComponent: ...
    @Sagittal.setter
    def Sagittal(self, value: SagittalAberrationComponent) -> None: ...
    @property
    def Tangential(self) -> TangentialAberrationComponent: ...
    @Tangential.setter
    def Tangential(self, value: TangentialAberrationComponent) -> None: ...

class SagittalAberrationComponent:
    Aberration_X = 0
    Aberration_Y = 1

class TangentialAberrationComponent:
    Aberration_Y = 0
    Aberration_X = 1
